- src/binding_context.hpp
- src/impl/android/external_commit_helper.cpp
- src/impl/external_commit_helper.hpp
- src/impl/transact_log_handler.cpp
- src/object_accessor.hpp
- src/parser/query_builder.hpp
- src/util/atomic_shared_ptr.hpp
This brings in the remaining handful of changes from realm-js's copy of the object store code. It'll allow realm-js to pull in object store's master branch directly.
> Pull in remaining changes from JavaScript

- .gitignore
> Add CMake generated files for the Xcode build system to .gitignore

- CMakeLists.txt
- src/impl/handover.cpp
- src/impl/handover.hpp
- src/impl/results_notifier.cpp
- src/impl/results_notifier.hpp
- src/list.cpp
- src/list.hpp
- src/parser/query_builder.cpp
- src/results.cpp
- src/results.hpp
- src/thread_confined.cpp
- tests/handover.cpp
- tests/list.cpp
- tests/results.cpp
- tests/transaction_log_parsing.cpp
> Update to core 1.5.0

- src/object_store.cpp
- tests/CMakeLists.txt
- tests/object_store.cpp
..which was lost somewhere in the schema updates.
> Reapply the change from #97

- src/object_store.cpp
@bdash, @kristiandupont or @fealebenpae  please review.
I think the problem lies in the handling of ternary expressions - I was unable to get any variation on them to compile for this `StringData` creation.
> workaround VS ternary expression compilation bug

- src/shared_realm.cpp
https://github.com/realm/realm-object-store/issues/142
@bdash @tgoyne
> Add schema change handler after handover begin read

- src/impl/realm_coordinator.cpp
- src/shared_realm.cpp
- tests/handover.cpp
- tests/list.cpp
- tests/results.cpp
- tests/transaction_log_parsing.cpp
@bdash @tgoyne @jpsim 
All tests pass.
> Update object store to support Core v2.*

- src/impl/transact_log_handler.cpp
- tests/list.cpp
> Add a missing check for current_table()

- src/shared_realm.cpp
> update shared_realm.cpp for new SharedGroupOptions

- tests/handover.cpp
- tests/transaction_log_parsing.cpp
Fix tests that were broken by https://github.com/realm/realm-object-store/pull/155
@jpsim @bdash
> Fix broken tests

- src/object_store.cpp
- src/object_store.hpp
export `set_schema_version()` for https://github.com/realm/realm-java/issues/3417
> export ObjectStore::set_schema_version()

- src/impl/transact_log_handler.cpp
Introduced in core 2.0.0-rc4
Change courtesy of @cmelchior 
/cc @bdash @tgoyne
> Handle the new add_int instruction

- src/object_accessor.hpp
> use unique instructions for pirmary int and string setters

- src/object_accessor.hpp
> populate the primary key column before writing other properties

- CMakeLists.txt
- src/impl/transact_log_handler.cpp
- src/object_store.cpp
- src/shared_realm.cpp
- tests/handover.cpp
- tests/transaction_log_parsing.cpp
- tests/util/test_file.cpp
- tests/util/test_file.hpp
And drop support for 1.x now that there's a non-beta release of 2.0.
> Update to core 2.0.0

- CMake/RealmCore.cmake
- src/impl/collection_notifier.hpp
- src/impl/realm_coordinator.cpp
- src/impl/realm_coordinator.hpp
- src/impl/transact_log_handler.cpp
- src/shared_realm.cpp
- src/shared_realm.hpp
- tests/CMakeLists.txt
- tests/realm.cpp
- tests/util/test_file.cpp
- tests/util/test_file.hpp
This is primarily some refactoring that @tgoyne did a little while ago, along with the beginning of support for tests against an in-process sync server.
> Fold in changes from the JS sync branch

- src/sync_config.hpp
- src/sync_manager.cpp
- src/sync_manager.hpp
- src/sync_session.cpp
- tests/CMakeLists.txt
- tests/realm.cpp
- tests/sync.cpp
- tests/util/event_loop.cpp
- tests/util/event_loop.hpp
- tests/util/test_file.cpp
- tests/util/test_file.hpp
This is primarily to get the infrastructure in place to allow testing of new changes.
/cc @austinzheng @tgoyne @jpsim
> Add some very basic sync tests

- src/impl/android/external_commit_helper.cpp
- src/impl/realm_coordinator.hpp
- src/shared_realm.cpp
- src/shared_realm.hpp
fix for realm/realm-java#3140
review this please @realm/java @beeender @kneth
> fix support for the filesystem which does not allow mkfifo

- CMake/RealmCore.cmake
- CMakeLists.txt
- README.md
- src/CMakeLists.txt
- src/impl/apple/keychain_helper.cpp
- src/impl/apple/keychain_helper.hpp
- src/impl/collection_notifier.cpp
- src/impl/collection_notifier.hpp
- src/impl/realm_coordinator.cpp
- src/impl/realm_coordinator.hpp
- src/impl/sync_client.hpp
- src/impl/transact_log_handler.cpp
- src/shared_realm.cpp
- src/shared_realm.hpp
- src/sync_config.hpp
- src/sync_manager.cpp
- src/sync_manager.hpp
- src/sync_metadata.cpp
- src/sync_metadata.hpp
- src/sync_session.cpp
- src/sync_session.hpp
- tests/CMakeLists.txt
- tests/realm.cpp
- tests/util/event_loop.cpp
- tests/util/test_file.cpp
- tests/util/test_file.hpp
> Pull over sync changes

- src/impl/realm_coordinator.cpp
> allocate static resources on the heap

- src/impl/collection_notifier.hpp
- tests/util/event_loop.cpp
- tests/util/event_loop.hpp
> Constructors required by GCC 4.9 when compiling for Android

- .dockerignore
- .gitignore
- Dockerfile
- Jenkinsfile
- workflow/docker_build_wrapper.sh
- workflow/local_docker_build.sh
- workflow/test_coverage.sh
@bdash @cmelchior This replaces #194 with a proper merge to master.
> Added CI harness for linux tests

- CMake/CodeCoverage.cmake
- Jenkinsfile
Also fixes processing coverage reports for out-of-source builds.
@bdash @alazier @sorenvind @radu-tutueanu
> Added macOS build to Jenkinsfile

- Jenkinsfile
> Publish reports after all builds

- src/sync/sync_session.cpp
The documentation for `sync::Session` states that they may be run after the `sync::Session` goes away, which means they may also be run after the `SyncSession` goes away. Capture a `weak_ptr` to `this` in the two callback lambdas so we can detect whether the `SyncSession` exists and guarantee it remains alive for the duration of the callback.
Fixes one of the problems noted in #207.
Needs:
> Make the sync transaction and error handler callbacks safe to run after the SyncSession has been destroyed

- src/results.cpp
- src/results.hpp
- tests/results.cpp
Closes #183 
To do:
@bdash @cmelchior @ironage
> Exposing core's distinct method

- tests/sync/session.cpp
- tests/util/test_file.cpp
> Fix compilation of sync tests

- src/sync/sync_user.cpp
- src/sync/sync_user.hpp
- tests/sync/session.cpp
@alazier  @bdash 
This might solve the issues we have seen in the ROS.
> Merge master into js

- src/util/android/event_loop_signal.hpp
Reverts realm/realm-object-store#331
Found some issues with this. Working on it now.
> Revert "Fix resource leaking in the android event loop"

- src/impl/collection_change_builder.cpp
- tests/collection_change_indices.cpp
Fixes https://github.com/realm/realm-object-server/issues/835
@sorenvind
> Update row move information for non-end insertions

- src/impl/realm_coordinator.cpp
We need to decide which version to advance to in the notifier worker while the notifier lock is held, as otherwise we may advance to a version that some notifiers needed to skip over and then trying to perform that skip will fail.
The problematic sequence of events was:
1. Notifier worker releases notifier lock
2. Thread with notifications acquires notifier lock
3. Thread with notifications commits write transaction
4. Thread with notifications sets skip version
5. Notifier worker advances to latest version
6. Notifier worker acquires notifier lock
7. Notifier worker tries to advance to skip version and fails
No new test for this as I don't know how to produce it other than hammering commits and hoping to hit the bad timing.
> Fix a race condition leading to bad version errors in the notifier worker

- tests/sync/session.cpp
The sync fix in https://github.com/realm/realm-sync/pull/1112, which fixes a sync deadlock related to progress notification blocks, allowed @bdash to uncover a new issue in our sync tests.
The issue is this: one of our tests relies on a session being destroyed right after leaving a block scope, which would ordinarily happen because the last pointer to that session goes out of scope. However, it's possible that, if certain things happen (the progress notifier callback is invoked at a certain point, causing another strong reference to the session to be generated), the session might not actually be destroyed immediately.
There was also another issue, but I've not been able to reproduce it after applying this fix. We can either hold this PR open as a way to track progress, or we can merge it …
> Apply Mark's fix to fix a sync test

- src/impl/collection_notifier.cpp
- src/impl/list_notifier.cpp
- src/impl/object_notifier.cpp
- src/impl/realm_coordinator.cpp
- src/impl/results_notifier.cpp
- src/impl/transact_log_handler.cpp
- src/impl/transact_log_handler.hpp
- src/shared_realm.cpp
- src/shared_realm.hpp
- src/thread_safe_reference.cpp
- tests/realm.cpp
- tests/transaction_log_parsing.cpp
Bindings could close Realm in the notify callbacks.
> Handle realm close in did_change callbacks

- src/results.cpp
- tests/results.cpp
Results's last() and first() should return none if the row is deleted.
> Check attached for snapshot last and first

- src/object_accessor.hpp
> Kill warning from gcc 4.9

- src/sync/sync_session.cpp
https://github.com/realm/realm-sync/pull/1187#issuecomment-290212966
> don't report pong_timeout errors to bindings

- Jenkinsfile
- src/shared_realm.cpp
- src/shared_realm.hpp
- tests/realm.cpp
needed for https://github.com/realm/realm-cocoa/issues/3289
interprocess tests will be done in cocoa PR
> Add should_compact_on_launch_function

- src/object.cpp
- tests/object.cpp
Fix https://github.com/realm/realm-java/issues/4502
> ObjectNotifier should not be registered again

- src/sync/sync_permission.cpp
- src/sync/sync_permission.hpp
- tests/CMakeLists.txt
- tests/sync/metadata.cpp
- tests/sync/permission.cpp
In support of https://github.com/realm/realm-cocoa/pull/4799
> Add two helper methods, so all bindings can use them

- src/sync/sync_permission.cpp
- src/sync/sync_permission.hpp
The first commit is the stuff Ari did. The second commit is the stuff I did to get it to compile. Apologies again for not checking the first time.
c.f. #448
> Reinstate key-value permissions changes

- src/sync/sync_user.cpp
- src/sync/sync_user.hpp
Required for https://github.com/realm/realm-cocoa/pull/4964
> Add a user info field to `SyncUser` for binding use

- src/parser/parser.cpp
I found this one quickly running the repo through `cppcheck`
> Fix a missing bracket

- src/util/uv/event_loop_signal.hpp
The EventLoopSignal destructor might be invoked on a thread other than the loop thread so we need to marshal the uv_close call to it.
> Always close the uv_async handle on the loop thread

- src/object_store.cpp
- tests/sync/session/session.cpp
As of sync v2.0, object store's `metadata` table is no longer being synced. This means that it's possible for a Realm to be downloaded and opened and contain the expected schema, even though it has no schema version set. If the Realm's schema doesn't match the schema specified by the app, this could lead to us performing non-additive schema changes, such as removing properties, in an effort to make the "new" Realm file have the schema we expect.
We address this by always using `apply_additive_changes` when updating the schema of a Realm using additive schema mode, rather than using `create_initial_tables` when the Realm has no schema version. This avoids ever attempting non-additive changes when in additive schema mode.
In addition, sync v2.0 no longer syncs the presence of indexes. This …
> Don't attempt to make non-additive schema changes to a synced Realm

- src/shared_realm.cpp
- tests/realm.cpp
when a Realm is already open at that path. Fixes Cocoa #5010 (https://github.com/realm/realm-cocoa/issues/5010).
> avoid calling should_compact_on_launch_function

- tests/sync/session/session.cpp
Updated client reset test to reflect changes added in https://github.com/realm/realm-object-store/pull/561
> update client reset test

- CMake/RealmCore.cmake
- src/sync/impl/sync_file.cpp
- src/sync/impl/sync_file.hpp
- src/util/event_loop_signal.hpp
- tests/sync/file.cpp
Two minor changes needed by .NET
> Allow overriding REALM_USE_UV

- src/sync/impl/sync_file.cpp
- src/sync/impl/sync_file.hpp
- src/util/time.hpp
- tests/sync/file.cpp
- tests/sync/sync_test_utils.cpp
realm-js is now testing this on CI and it turns out it never worked.
> Fix sync-enabled Windows compilation

- src/schema.cpp
- src/sync/impl/work_queue.hpp
- tests/schema.cpp
Fixes the underlying issue identified in https://github.com/realm/realm-cocoa-private/issues/382.
> Validate that a given type appears at most once in the schema

- src/impl/realm_coordinator.cpp
- src/impl/realm_coordinator.hpp
- src/object.cpp
- src/object_accessor.hpp
- src/shared_realm.cpp
- src/shared_realm.hpp
- src/thread_safe_reference.cpp
- src/thread_safe_reference.hpp
- tests/realm.cpp
- tests/thread_safe_reference.cpp
tests/realm.cpp
tests/thread_safe_reference.cpp
> Enabling some more tests

- src/shared_realm.cpp
- src/shared_realm.hpp
- tests/realm.cpp
Used to solve https://github.com/realm/realm-js/issues/1881
> Adding compute_size() method

- src/impl/realm_coordinator.cpp
- src/impl/results_notifier.cpp
- src/list.cpp
- src/list.hpp
- src/results.cpp
- src/results.hpp
- src/shared_realm.hpp
- src/thread_safe_reference.cpp
- src/thread_safe_reference.hpp
- tests/list.cpp
- tests/primitive_list.cpp
- tests/results.cpp
The tests not yet passing are commented out. They should - however - be able to compile.
> Make more List and Results tests work

- src/results.cpp
- tests/results.cpp
Includes a fix for Results::max and Results::min
> More Results test

- src/results.hpp
- tests/results.cpp
Fix for: https://github.com/realm/realm-java/issues/6478
> Fix crash with batch update if object is removed from Results

- src/sync/sync_session.cpp
- src/sync/sync_session.hpp
- tests/sync/partial_sync.cpp
- tests/sync/session/session.cpp
Required for https://github.com/realm/realm-cocoa/pull/6136.
> Add support for updating the configuration of an existing sync session

- src/impl/collection_notifier.cpp
- src/impl/collection_notifier.hpp
- src/impl/results_notifier.cpp
- tests/results.cpp
> Adapt to changed table version handling in core

- src/sync/sync_session.cpp
> Fix build error on Windows

- .vscode/cmake-variants.yaml
- .vscode/extensions.json
- .vscode/settings.json
- README.md
- tests/CMakeLists.txt
Please see changes in `README.md`.
> Add tooling for Visual Studio Code

- src/object_store.cpp
- tests/migrations.cpp
- tests/sync/partial_sync.cpp
Depends on a new core6 release and should be merged as part of updating to that.
> Update primary key changing to work with latest core

- src/server/global_notifier.cpp
if the file does not exists do not crash when trying to delete it.
> don't crash on missing file when deleting it

- src/object_store.cpp
- src/object_store.hpp
- tests/object_store.cpp
This will probably require SDKs to update a bunch of call sites, but the naming is more correct.
> property_for_column_index -> property_for_column_key

- src/sync/app.cpp
- src/sync/app.hpp
- src/sync/generic_network_transport.cpp
- src/sync/generic_network_transport.hpp
- src/sync/impl/sync_metadata.cpp
- src/sync/sync_manager.cpp
- src/sync/sync_manager.hpp
- src/sync/sync_user.cpp
- src/sync/sync_user.hpp
- tests/sync/app.cpp
- tests/sync/metadata.cpp
- tests/sync/user.cpp
App now contains `switch_user(user_id)` & `remove_user(user_id)`
> Add ability to switch and remove user

- src/util/event_loop_dispatcher.hpp
- tests/sync/app.cpp
- tests/sync/session/session.cpp
- tests/sync/sync_manager.cpp
- tests/util/test_file.cpp
Improve some tests, remove some dead code and "FIXME" comments.
> Misc cleanup

- src/sync/sync_session.cpp
- src/sync/sync_session.hpp
In order to fix - at least partially - https://jira.mongodb.org/browse/RJS-347
> Surface client reset

- src/sync/app.cpp
- src/util/event_loop_dispatcher.hpp
Fixes building on windows with vs2019
> fix building on windows with vs2019

- src/impl/realm_coordinator.cpp
- src/impl/realm_coordinator.hpp
- src/impl/results_notifier.cpp
- src/impl/weak_realm_notifier.cpp
- src/impl/weak_realm_notifier.hpp
- src/keypath_helpers.hpp
- src/shared_realm.cpp
- src/shared_realm.hpp
- src/util/android/scheduler.hpp
- src/util/apple/scheduler.hpp
- src/util/generic/scheduler.hpp
- src/util/scheduler.cpp
- src/util/scheduler.hpp
- src/util/uv/scheduler.hpp
- tests/list.cpp
- tests/migrations.cpp
- tests/object.cpp
- tests/primitive_list.cpp
- tests/realm.cpp
- tests/results.cpp
- tests/thread_safe_reference.cpp
- tests/transaction_log_parsing.cpp
This merges latest master into v10 (notably pulls the Realm caching mechanism)
> Merge master into v10

- src/list.cpp
- src/list.hpp
- tests/list.cpp
This just proxies Core's API for SDKs that can't use the Accessor APIs.
> Expose List API for adding, inserting, and setting embedded objects

- src/sync/app.cpp
Reported here https://github.com/realm/realm-java/issues/7116
> Reset password was sending the wrong parameter

- src/object_store.cpp
- tests/migrations.cpp
If a property both had a change in nullability and was set as the new primary key property, we ended up using the wrong ColKey.
When changing the nullability, the col key changes, but the value in the change set was taken before migration started.
Fixes https://github.com/realm/realm-js/issues/3270
> Fix bug around change of nullability

- src/sync/app_utils.hpp
- src/sync/generic_network_transport.hpp
- tests/sync/app.cpp
Fixes https://github.com/realm/realm-object-store/issues/1102
> add the link to server error logs to AppError when present

- src/schema.cpp
- tests/schema.cpp
Fixes https://github.com/realm/realm-object-store/issues/1065
> schema check for embedded object loops

- src/object_schema.cpp
- src/object_schema.hpp
- src/schema.cpp
- src/schema.hpp
- src/shared_realm.cpp
- tests/object.cpp
- tests/realm.cpp
- tests/results.cpp
- tests/schema.cpp
- tests/sync/app.cpp
- tests/sync/session/session.cpp
- tests/sync/sync_manager.cpp
- tests/util/test_utils.hpp
Requested by https://github.com/realm/realm-object-store/issues/923
Hopefully this doesn't break too many SDK level tests.
> non _id pks generate a schema error for sync realms

- src/impl/windows/external_commit_helper.hpp
remove forgotten dead private member m_name
> remove dead private member m_name

- src/CMakeLists.txt
- src/sync/app_credentials.cpp
- src/sync/app_credentials.hpp
- src/util/tagged_string.hpp
- tests/sync/app.cpp
Backport https://github.com/realm/realm-core/pull/4138
> Add Google credential for openId

- src/CMakeLists.txt
- src/sync/app.cpp
- src/sync/app.hpp
- src/sync/subscribable.hpp
- src/sync/sync_user.cpp
- src/sync/sync_user.hpp
- tests/sync/app.cpp
Backport https://github.com/realm/realm-core/pull/4087
> Make App and SyncUser subscribable
