realm/realm-object-store

src/binding_context.hpp, src/impl/list_notifier.cpp, src/impl/list_notifier.hpp, src/impl/realm_coordinator.cpp, src/impl/realm_coordinator.hpp, src/impl/transact_log_handler.cpp, src/impl/transact_log_handler.hpp, src/list.cpp, src/object_accessor.hpp, src/object_schema.cpp, src/object_schema.hpp, src/object_store.cpp, src/object_store.hpp, src/property.hpp, src/results.cpp, src/schema.cpp, src/schema.hpp, src/shared_realm.cpp, src/shared_realm.hpp, tests/CMakeLists.txt, tests/collection_change_indices.cpp, tests/index_set.cpp, tests/list.cpp, tests/migrations.cpp, tests/realm.cpp, tests/results.cpp, tests/schema.cpp, tests/transaction_log_parsing.cpp
Add the concept of "schema modes" which control how updates to the schema are handled. Currently there are five:
1. Automatic: the Cocoa binding's default mode. Adding new tables and adding or removing indexes is always allowed. Adding, removing, or modifying a property, or changing the primary key requires incrementing the schema version. The migration function is called whenever the schema version is increased.
2. Read-only: open the file in read-only mode, allow missing or extra tables, allow index mismatches, and error on all other differences.
3. Reset file: allow adding new tables or adding/removing indexes. All other changes (including bumping the schema version) result in the file being deleted and recreated. Does not work with multi-process.
4. Additive-only: Allowing adding new …
=> Redesign schema handling and add additive-only mode

src/schema.cpp, src/schema.hpp
This gives a surprisingly large speedup for Realm instance init.
=> Eliminate some string copies for Schema::find()

tests/schema.cpp
The overload of `toString` we were providing wasn't being picked up by Catch, and so was never being called. Switch to their suggested alternative approach of providing a specialization of `StringMaker`. This specialization is correctly picked up by Catch.
/cc @tgoyne
=> Fix warning about toString being unused when building tests

src/impl/realm_coordinator.cpp, src/shared_realm.hpp
Addresses https://github.com/realm/realm-object-store/issues/117 //cc @bdash @tgoyne
=> Ensure manipulation of `Realm` must go through a `SharedRealm`

src/schema.cpp, tests/migrations.cpp
Removing a column invalidates the cached table columns for all columns after
that, so group removes after all other changes and sort them in descending
order of table column to avoid ever invalidating a yet-to-be-applied change.
See https://github.com/realm/realm-cocoa/issues/3943
@bdash
=> Fix incorrect results when removing multiple properties from a single object

src/impl/handover.cpp
All include paths need to be relative to `src` for non-Xcode/CMake builds to work.
=> Fix include path for handover.hpp

src/impl/transact_log_handler.cpp, src/object_store.cpp
An upcoming version of core has some small API differences. For now we want to support building with both the currently-released version (1.5.x) and the upcoming version (2.x), so we key off the `REALM_VER_MAJOR` define to use the appropriate code path.
=> Accommodate API changes in newer version of core

.gitignore, src/CMakeLists.txt, tests/CMakeLists.txt
The presence of the dynamic library predates the object store having its own test suite, and was used to catch link errors due to bugs in object store or missing symbols in core. It is no longer needed for this purpose now that object store has a proper test suite.
Removing the dynamic library also works around some linker problems that reveal themselves when using a version of core built with Xcode 8. See https://github.com/realm/realm-object-store/pull/136#issuecomment-242897308 for the gory details.
/cc @tgoyne
=> Switch to building the object store as a static library only

src/impl/transact_log_handler.cpp, tests/list.cpp
Non-end row insertions and move_last_over() can move the row containing a List being observed, which was not being handled correctly.
=> Fix incorrect row index updating for List notifications

src/impl/transact_log_handler.cpp, tests/list.cpp
Requires https://github.com/realm/realm-core/pull/2093 to actually work in a useful way.
All other notification types also have issues related to objects being subsumed which need to be addressed separately.
=> Handle Lists moving due to unique key reuse

src/results.cpp
We previously did not set up the notifier until `update_tableview` was called while `m_mode` was `Mode::TableView`. This led to us not creating the notifier until the second access (since `m_mode` is query on the first access when the table view is created). This PR corrects this buggy behavior to what was intended.
Note that this fall through leads to `sync_if_needed` being unnecessarily called, but it's supposedly cheap. We could duplicate the notifier setup code in the query case if we're worried about this.
//cc @bdash @tgoyne
=> Set up notifier immediately after creating results table view

src/object_store.cpp, src/object_store.hpp
Object store always creates both metadata and pk table when creating a new Realm database.
This change aligns the behavior of Realm Java to ObjectStore. It is also required from realm/realm-java#3424
At first, I was thinking that I should expose `create_metadata_tables()` separately to be able to call it only at the creation of Realm, but finally I always call `create_metadata_tables()` from the `ObjectStore::set_schema_version()` since current OS always calls it on schema change.
=> Create metadata and pk table when set the schema version

src/object_store.cpp
The schema version table doesn't need it because we always read and write row zero.
=> Use set_string_unique() for the pk table

src/binding_context.hpp, src/impl/collection_change_builder.cpp, src/impl/collection_change_builder.hpp, src/impl/results_notifier.cpp, src/impl/transact_log_handler.cpp, tests/collection_change_indices.cpp, tests/handover.cpp, tests/list.cpp, tests/results.cpp, tests/transaction_log_parsing.cpp, tests/util/test_file.cpp, tests/util/test_file.hpp
This adds handling for row swapping, primary key conflict resolution, and SetDefault to the transaction log handler used for collection notifications, along with fixes to the changeset calculation to handle the fact that rows in table order can move in more ways now.
=> Implement remaining transaction log instructions for collection notifications

src/impl/transact_log_handler.cpp
Using < gives a false-positive if the change is in a table before an observed one.
=> Fix the check for if there is an observer for `from` in change_link_targets

src/shared_realm.cpp
Otherwise any new Realm instances created will use stale column indices.
=> Update the coordinator's copy of the schema after a schema change from another process

CMakeLists.txt, README.md, src/CMakeLists.txt, src/impl/realm_coordinator.cpp, src/shared_realm.cpp, src/shared_realm.hpp, tests/CMakeLists.txt
This PR merges `master` into `cocoa` and introduces a `REALM_ENABLE_SYNC` CMake option, which defaults to `OFF`.
Would love to know if there's a better way to do this @bdash. I'd rather not check for the presence of `REALM_SYNC_PREFIX` since when building realm cocoa the source for sync may not be available.
=> Conditionally build sync

src/impl/apple/keychain_helper.cpp, src/impl/apple/keychain_helper.hpp
`size_t` is an unsigned type, so using it was resulting in a large positive error code being printed for keychain errors, rather than the real small negative error code.
/cc @austinzheng
=> Fix the type used for the error code for KeychainAccessException.

src/impl/results_notifier.cpp
The version for reused handover objects was being bumped on delivery to the most recent version that had been calculated, which may be more recent than the version actually being delivered. Instead bump it to the point where we would normally recreate the handover object so that it is guaranteed to get the correct version.
No new test for this because it was a race condition and thus not meaningfully testable. Fixes https://secure.helpscout.net/conversation/259511081/6838/ and probably fixes realm/realm-cocoa#4144.
@bdash
=> Fix a BadVersion exception when async notifiers run during delivery

src/impl/collection_notifier.cpp, src/impl/collection_notifier.hpp, src/impl/realm_coordinator.cpp, src/impl/realm_coordinator.hpp, src/impl/transact_log_handler.cpp, src/impl/transact_log_handler.hpp, src/shared_realm.cpp, src/shared_realm.hpp, tests/handover.cpp
Eliminates a bit of cruft done to avoid dragging in group_shared.hpp.
=> Use unnested VersionID

src/sync_session.cpp, src/sync_session.hpp
@tgoyne @bdash 
I pulled this small change out of https://github.com/realm/realm-object-store/pull/181, since it's not related to the deadlocks that issue tries to address.
`bind()` must be called before `wait_for_upload_complete_or_client_stopped()` and `wait_for_download_complete_or_client_stopped()` can be called; this change enforces that precondition
=> Fix an issue where the "wait for upload/download" APIs could cause an error

src/shared_realm.cpp, src/shared_realm.hpp, tests/migrations.cpp
The Realm's schema needs to be set to the passed-in schema even if no changes are needed as the schema from disk may include additional object types that are not in the requested schema. This was already done properly for all schema modes except for ResetFile.
See https://github.com/realm/realm-cocoa/issues/4190.
=> Set the schema properly when no changes are needed in ResetFile mode

src/impl/realm_coordinator.cpp, src/impl/realm_coordinator.hpp
The current version of the notifier was being checked rather than the version of the notifier's prepared handover object, which could result in a BadVersion exception if the notifier happens to run in between when the handover object is packaged for delivery and when the version is checked.
Fixes the repo case from https://github.com/realm/realm-cocoa/issues/3412#issuecomment-253185742.
=> Fix a race condition when delivering collection notifiers

CMakeLists.txt, src/sync_session.cpp
Sync beta 3.1 adds some new error types that need to be handled.
=> Update to core 2.1.3/sync beta 3.1

CMake/RealmCore.cmake
/usr/local is not on the default search path when building via Xcode, so a simple `-lyaml-cpp` doesn't work when it's installed via homebrew. Fix this by using pkg-config to get the correct ldflags.
=> Fix compilation in Xcode with sync enabled

CMake/RealmCore.cmake
Got `ld: library not found for -lFoundation` error, `Foundation` and `Security` frameworks are specified as libraries when linking.
/cc @bdash
=> Fix linking with CoreFoundation and Security frameworks

src/sync/sync_user.cpp
due to `m_sessions`/`m_waiting_sessions` being a map to `weak_ptr`, there could be a key entry with no corresponding `SyncSession`.
Thanks @bdash for finding this.
=> fix check for already-registered sessions in SyncUser::register_session

src/sync/sync_manager.cpp, src/sync/sync_session.cpp, src/sync/sync_session.hpp, src/sync/sync_user.cpp, src/sync/sync_user.hpp, tests/sync/file.cpp, tests/sync/metadata.cpp, tests/sync/session.cpp, tests/sync/sync_manager.cpp, tests/sync/user.cpp
@alazier @bdash @tgoyne 
This PR doesn't fix any bugs, it just adds some more sync-related tests and improves a few peripheral things. So there's no rush to get it reviewed.
Changes:
- Added more tests examining the interaction between `SyncUser` and `SyncSession`
- Renamed `SyncSession`'s `is_inactive()` API to `can_be_safely_destroyed()` to better reflect its purpose
- Added a `SyncSession` API to examine the current state, and removed the `is_valid()` API
- Tagged existing sync-related tests with the `[sync]` tag
=> Improve object server test suite

src/impl/realm_coordinator.cpp
Fixes a crash in some of the async error handling paths that the obj-c tests were intermittently hitting on CI.
=> Don't assert the state of the worker SG if it doesn't exist

tests/sync/session.cpp, tests/sync/user.cpp
Tests fix in https://github.com/realm/realm-object-store/pull/219
Before the fix, this test never completes. After the fix, it works.
There's probably a more idiomatic way to pass a second value out of a function...
@bdash @jpsim @tgoyne
=> Add a test for sync session re-registration

CMake/RealmCore.cmake
This avoids polluting the source directory when doing an out of source build.
=> Put core's files within the build directory rather than the source directory

src/sync/sync_session.cpp
GCC on Linux evaluates function arguments in a different order to Clang on Apple platforms, as is its right. This was resulting in a null dereference due to dereferencing a moved-from `shared_ptr`.
=> Fix a crash seen when running the sync tests on Linux

src/sync/sync_manager.cpp, src/sync/sync_manager.hpp, tests/sync/sync_manager.cpp
This PR is related to https://github.com/realm/realm-cocoa/issues/4264, it allows to reset metadata in case of error, most likely in case of invalid encryption key. Other related issues: https://github.com/realm/realm-browser-osx/issues/228 and https://github.com/realm/realm-browser-osx-private/issues/141.
Any existing users directories should probably be deleted at least until we have an API to handle this as was suggested in https://github.com/realm/realm-cocoa/issues/4264.
/cc @austinzheng, @jpsim, @bdash
=> Reset metadata if metadata.realm could not be opened

src/util/uv/event_loop_signal.hpp
Deleting an object through a different pointer type gives undefined behavior, and elicits a complaint from address sanitizer.
/cc @alazier
=> Delete the uv_async_t through the correct pointer type

src/sync/sync_manager.cpp, tests/sync/session.cpp
Reported by @mrackwitz in #178.
/cc @austinzheng
=> Don't deadlock when SyncUser::register_session complains about registering multiple sessions for the same URL

src/object_schema.cpp, src/object_schema.hpp, src/object_store.cpp, src/schema.cpp, tests/migrations.cpp
Backlink columns should not be inserted directly to tables. This happens automatically when the corresponding Link or LinkList column is inserted in the linked table. This caused the stack trace in realm core [2291](https://github.com/realm/realm-core/issues/2291). The added test in this PR can produce the same stack trace.
@bdash @tgoyne please review
=> Fix property change migration involving LinkingObjects

src/impl/collection_notifier.cpp, tests/results.cpp
refresh() and begin_write() don't block for notifiers if the notifiers exist only for implict async queries and there are no callbacks, which means that the Realm can get ahead of the notifier version. When this happened, it was still trying to advance to the notifier version even though nothing from that notifier would be delivered and the advance would fail due to it being an older version.
Probably is the issue reported at https://github.com/realm/realm-cocoa/issues/4345.
=> Fix a LogicError(bad_version) error on refresh()

src/shared_realm.cpp, src/sync/impl/sync_metadata.cpp, tests/realm.cpp, tests/util/test_file.cpp
Reject a few more cases such as supplying a schema without a schema version or a migration function in a schema mode that doesn't do migrations.
Closes #249.
=> Add more validation for Realm Config parameters

src/sync/sync_manager.cpp, src/sync/sync_manager.hpp, tests/sync/sync_manager.cpp
@jpsim @bdash @tgoyne 
Related to: https://github.com/realm/realm-object-store/issues/231
Changes:
- `SyncManager` now only returns logged-in, non-errored users
- Added more tests
=> Change `all_users` to `all_logged_in_users`

src/shared_realm.cpp, src/shared_realm.hpp
Realm Java has a bit of a complex flow when initializing a Realm file. Breaking it up to smaller transactions might leave the Realm file in an inconsistent state. 
@cmelchior @beeender @bdash
=> Allow caller of update_schema() to handle transaction

src/sync/sync_manager.cpp, src/sync/sync_manager.hpp, src/sync/sync_session.cpp, src/sync/sync_session.hpp, tests/results.cpp, tests/sync/session.cpp
Fixes #178, fixes #244
Depends upon: #241 (otherwise the tests will still sporadically fail)
@bdash 
Changes:
- Replaced use of blocking waiter APIs with their new async variants
- Updated tests
- Test resetter now clears sessions between test runs
=> Replace blocking upload/download waiters with async versions

src/impl/apple/external_commit_helper.cpp
It's deprecated in favor of os_log, but os_log is only available when targeting macOS 10.12/iOS 10 so it'll be a very long time before we can switch to it.
=> Disable deprecation warnings for ASL

src/sync/sync_session.cpp
Seems like `realm::sync::Error` was renamed to `ProtocolError`, so building OS against latest sync fails.
=> Fix errors for sync beta 5.0

src/results.cpp, src/results.hpp
One of the constructors added in #235 did not set m_table, which broke `sort()` even when not using `distinct()`.
@jpsim
=> Remove redundant Results constructors and set m_table in all of them

tests/util/test_file.cpp
Failing to close this file descriptor results in many tests failing on macOS Sierra due to running out of available file descriptors.
/cc @kneth @austinzheng
=> Close the file descriptor returned by mkstemp

src/sync/impl/sync_client.hpp, src/sync/sync_manager.cpp, src/sync/sync_manager.hpp, src/sync/sync_session.cpp, src/sync/sync_session.hpp
`SyncClient`'s lifetime was managed by a `shared_ptr`, resulting in `SyncManager::reset_for_testing` failing to destroy it when expected. This meant that its runloop was still running, and that it could continue to deliver callbacks to sessions that `reset_for_testing` was in the process of destroying.
To address this `SyncClient` is now owned by `SyncManager`, with `SyncSession`'s holding only a reference to their client. This is safe because sync asserts that all sessions have been destroyed when the client is destroyed.
/cc @austinzheng @alazier 
Fixes #269.
=> Fix a crash when calling SyncManager::reset_for_testing

src/CMakeLists.txt, src/sync/sync_manager.cpp, src/sync/sync_manager.hpp, src/sync/sync_notifier.hpp, src/sync/sync_session.cpp, src/sync/sync_user.cpp, src/sync/sync_user.hpp, tests/sync/session.cpp, tests/sync/sync_manager.cpp, tests/sync/sync_test_utils.cpp, tests/sync/sync_test_utils.hpp, tests/sync/user.cpp
@bdash
Implement a notifier for the `SyncManager` for use by bindings.
Changes:
- Implemented a notifier that bindings can override to get sync-wide event notifications
- A few internal API changes to facilitate this new feature
- Object store sync test infrastructure slightly overhauled to facilitate testing
- Added tests to exercise the new functionality
=> Add support for an event notifications mechanism

src/sync/sync_user.cpp, src/sync/sync_user.hpp, tests/sync/session.cpp
Replaces #270. @bdash @simonask 
Fixes #243.
Changes:
- ~~`Realm::Config` now has a method to properly configure itself with a `SyncConfig`~~
- Sync users now index sessions by their on-disk paths, allowing multiple sessions per URL (as long as their file paths are distinct)
- The `session_for_url()` API has been removed
- Updated tests
=> Support multiple SyncSessions per URL

src/sync/sync_manager.cpp, src/sync/sync_manager.hpp, tests/sync/sync_manager.cpp
With the API exposed in OS, bindings won't have to implement it themselves.
=> Expose current user in sync_manager

src/impl/realm_coordinator.cpp, src/impl/transact_log_handler.cpp, src/impl/transact_log_handler.hpp, src/shared_realm.cpp, tests/transaction_log_parsing.cpp
The checks for things which are valid for additive-only but not automatic Realms was not being consistently applied, and fixing this isn't really worth the effort as everything either works or fails in a sensible way anyway. The checks for destructive changes remain as they actually provide some value (without the validation, trying to use a column which was deleted by a different process would produce mysterious crashes not obviously related to the root problem), and are already being always used.
=> Remove some transaction log validation for schema changes

src/CMakeLists.txt, src/execution_context_id.hpp, src/impl/realm_coordinator.cpp, src/impl/weak_realm_notifier.cpp, src/impl/weak_realm_notifier.hpp, src/shared_realm.cpp, src/shared_realm.hpp, src/util/aligned_union.hpp, tests/realm.cpp
This can be used by bindings that wish cached Realms to be keyed on something other than the thread they were created on, such as a JavaScript context or Python interpreter state.
Related to realm/realm-js#552, and will allow realm-js to easily fix realm/realm-js#473.
This should allow the thread ID changes from c34b3db85d86bf542fb57cd34f393efeac87b929 to be dropped from the `js` branch, making it possible for realm-js to use master directly.
=> Introduce the concept of an abstract execution context

src/impl/realm_coordinator.cpp
This brings #202 to `master` from `js`, and also fixes the lifetime of `s_coordinator_mutex` in a similar way, fixing an exception being thrown during quit that the JS binding was still working around.
=> Bring changes to lifetime of statics in realm_coordinator.cpp to master

src/shared_realm.cpp, src/shared_realm.hpp, tests/realm.cpp
This brings @kristiandupont's changes to the JS branch from #278 over to master, with the addition of some basic testing.
This is the only remaining change in `js` but not `master`.
=> Bring verify_open to master

src/impl/transact_log_handler.cpp, tests/transaction_log_parsing.cpp
Table moves had an off-by-one error, and columns being moved to a higher index did completely the wrong thing with any modifications made before the move.
=> Fix some incorrect handling of schema changes in the notification code

src/shared_realm.hpp
This was made on the `js` branch but had not made it over to `master`.
=> Allow GlobalNotifier to access the functions declared in Realm::Internal

src/shared_realm.cpp
As requested in realm/realm-cocoa#4470. An alternative would be to require that both `deleteRealmIfMigrationNeeded` _and_ `disableFormatUpgrade` be set to enable this behavior. I have a test in Realm Objective-C since we don't seem to have object store tests related to file format upgrades, or sample Realms in this repo.
/cc @bdash @tgoyne
=> reset file if a file format upgrade is required in ResetFile mode

src/impl/handover.cpp, src/impl/handover.hpp, src/impl/results_notifier.cpp, src/impl/results_notifier.hpp, src/thread_confined.cpp, tests/handover.cpp, tests/results.cpp
- Handover patch for Results.m_distinct
- Add tests
async distinct is supported by current java implementation, and for https://github.com/realm/realm-java/pull/3834 , it needs to be supported in OS level as well.
I am not quite sure if it is possible to make the fine grained notification work for the distinct results. Any suggestions? @bdash @tgoyne @JadenGeller
=> Handover for distinct Results

src/impl/epoll/external_commit_helper.cpp, src/util/android/event_loop_signal.hpp
Gcc 4.9: "iso c does not permit named variadic macros"
=> Fix compile warning -Wvariadic-macros

src/impl/epoll/external_commit_helper.cpp
It is just because of the fifo is full. Clear the fifo and retry.
See https://github.com/realm/realm-java/issues/3964
=> Write to fifo could fail with EAGAIN

src/impl/realm_coordinator.cpp, src/shared_realm.cpp, src/shared_realm.hpp, tests/realm.cpp
The GN needs to open Realms without specifying a schema, while in the same process the user needs to be able to open the same Realm, on the same thread/execution context and specify a schema. The code previously assumed that this switch would never happen, and so it would either throw an exception or outright ignore the supplied schema, depending on the sequence things were supplied and whether or not caching was enabled.
Fixes https://github.com/realm/realm-object-server/issues/737 and similar issues that anyone trying to use the GN would probably eventually hit.
=> Add proper support for opening a Realm without a schema and then with a schema

src/sync/impl/sync_metadata.cpp, src/sync/impl/sync_metadata.hpp, tests/sync/metadata.cpp, tests/sync/sync_test_utils.cpp, tests/sync/sync_test_utils.hpp
Changes
- Added `SyncFileActionMetadata`, which represents an action the file subsystem should take on a sync’ed Realm the next time the app launches
- Added tests
Part of client support for client reset.
=> Add support for “file action” sync metadata

src/binding_context.hpp, src/shared_realm.cpp
This is needed by java binding to integrate the Results and keep the
current realm-java collection iterator behaviour:
When write transaction begins, all collections on that thread have to be
frozen (stop calling sync_if_needed) until next event loop.
Since there is no way to inject code to be ran at the end of current
loop, realm-java needs to refresh the Results at the very beginning of
the next event loop as much as possible.
java could use binding_context::changes_available for transaction
committed by other threads, but there is no place to refresh all Results
if the transaction has been committed locally and async callback called
in the process_available_async. CollectionChangeCallback::after cannot
be used in this case since we have to ensure all the collections are
refreshed …
=> Add before_notify to binding_context

src/sync/impl/sync_file.cpp, src/sync/impl/sync_file.hpp, src/sync/impl/sync_metadata.cpp, src/sync/impl/sync_metadata.hpp, src/sync/sync_config.hpp, src/sync/sync_manager.cpp, src/sync/sync_manager.hpp, src/sync/sync_session.cpp, src/sync/sync_session.hpp, tests/sync/metadata.cpp, tests/sync/session.cpp, tests/sync/sync_manager.cpp, tests/sync/sync_test_utils.cpp, tests/sync/sync_test_utils.hpp
Changes:
- When receiving a 'diverging histories' error, a client reset file action is generated
- `SyncManager` now acts on file reset actions
- `SyncError` now has a user info map
- Added more tests
Note that I had a review for this branch but I accidentally completely destroyed it when I erased the `az/client-reset` branch. @jpsim
=> Allow sync file manager to act on "client reset" file actions

CMakeLists.txt, src/sync/impl/sync_file.cpp, tests/sync/session.cpp
`std::put_time` is not supported by GCC 4.9. This is a hack to get around it.
See also http://stackoverflow.com/questions/14136833/stdput-time-implementation-status-in-gcc
=> Adding gcc 4.9 support

src/impl/transact_log_handler.cpp, src/shared_realm.cpp, src/shared_realm.hpp, tests/realm.cpp, tests/results.cpp
Allow calling `refresh()` and send notifications as usual when beginning a write transaction from the `changes_available()` notification.
Make `invalidate()` a no-op when called from within a notification as with `refresh()` since it doesn't have sensible semantics when there are additional notifications to be delivered.
Fix a crash when advancing the read transaction version from within `did_change()` by beginning a write transaction when there are async queries. This still breaks sensibly delivering correct fine-grained notifications.
Fixes #317.
=> Fix some issues related to changing the read transaction version from within notifications

src/util/android/event_loop_signal.hpp
To fix https://github.com/realm/realm-java/issues/4002
The problems:
- Android thread may have a looper, but it may not be looping (eg:
IntentService). Also the looper could quit by calling Looper.quit().
This means if we rely on the looper callback to do clean up, many
things will be leaked because of the looper callback might not be
called at all.
- Passing pointers through pipe sounds dangerous. There would be many
cases the pipe has some pointers left without deletion.
Things need to be considered:
- The EventLoopSignal can be destroyed in a different thread because of
java GC.
- Looper callback should always have a valid pointer to use.
- We have to do clean up in the destructor.
Solution:
- Maintain a EventLoopSignal weak_ptr list and protect it with lock. So
the callback can either …
=> Fix resource leaking in the android event loop

src/CMakeLists.txt, src/binding_context.hpp, src/collection_notifications.hpp, src/impl/collection_change_builder.cpp, src/impl/collection_change_builder.hpp, src/impl/collection_notifier.cpp, src/impl/collection_notifier.hpp, src/impl/object_notifier.cpp, src/impl/object_notifier.hpp, src/impl/realm_coordinator.cpp, src/impl/realm_coordinator.hpp, src/impl/transact_log_handler.cpp, src/impl/transact_log_handler.hpp, src/index_set.hpp, src/object.cpp, src/object.hpp, src/object_accessor.hpp, src/shared_realm.cpp, src/shared_realm.hpp, src/thread_safe_reference.cpp, src/thread_safe_reference.hpp, tests/CMakeLists.txt, tests/collection_change_indices.cpp, tests/list.cpp, tests/object.cpp, tests/realm.cpp, tests/thread_safe_reference.cpp, tests/transaction_log_parsing.cpp, tests/util/index_helpers.hpp
Most of this is just refactoring to merge the two separate sets of transaction log parsing logic, so that the parser for the collection notifiers now (optionally) tracks which columns were modified, and the KVO stuff now uses that parser rather than a separate one.
With that done the object notifier itself is pretty trivial and straightforward.
=> Add a single-object "collection" notifier

src/object_accessor.hpp, src/shared_realm.hpp
The signature for Object::get_for_primary_key_impl was changed in #324 but a couple of callsites were not updated.
=> Fix calls to Object::get_for_primary_key_impl

src/impl/transact_log_handler.cpp
Using list-initialization for the base class zero-initializes the member variables, while the default constructor does not.
Fixes #344.
=> Properly initialize KVOAdapter::track_all

src/results.cpp
CSE warns that `result_ndx` is uninitialized at the point of use due to that it can't see where the variable is assigned to.
=> Silence some clang static analyzer false-positives

src/impl/collection_notifier.cpp, src/impl/results_notifier.cpp, tests/list.cpp, tests/object.cpp, tests/results.cpp
The skip flag was only cleared if a notification would actually have been delivered, which resulted in the *next* transaction's notification being skipped if a transaction did not actually do anything which would produce a notification.
Reported by https://github.com/realm/realm-cocoa/issues/4558.
=> Fix skipping notifications for transactions with no relevant changes

src/impl/realm_coordinator.cpp, src/impl/realm_coordinator.hpp, src/list.cpp, src/list.hpp, src/object.cpp, src/object.hpp, src/results.cpp, src/results.hpp, tests/object.cpp, tests/results.cpp
`unregister()` was never actually being called, so object notifiers would never get destroyed.
Add an assertion to the beginning of some of the test cases that there are no realms already open to catch this sort of thing before we hit the max file open limit.
Fixes #340.
=> Fix a retain cycle in the object notifier

src/object_store.cpp
We have a crash on a number of Android devices. We cannot trigger the crash in any unit tests (Realm Object Store or Realm Java) but only in the Realm Java's intro-example (and users' apps). During debugging sessions, I have found that swapping the order to the creation of the metadata and primary key tables "fixes" the issue.
As it crashes deep in Realm Core, the origin of the bug is still unclear.
Realm Java is getting some heat from the community for not releasing this temp. solution. The Realm Java team (with help from the Realm Core team) will continue the investigation after the merge of this PR.
See https://github.com/realm/realm-java/issues/3651
=> Temp. solution of https://github.com/realm/realm-java/issues/3651

src/sync/impl/sync_file.cpp, src/sync/impl/sync_file.hpp, src/sync/sync_manager.cpp, src/sync/sync_manager.hpp, tests/sync/sync_manager.cpp, tests/sync/sync_test_utils.cpp
Changes:
- Fixed a bug where the recovery path saved to the file action metadata was not the one expected when the metadata was read back out
- Refactored code that handles file actions into its own method
- Code that handles file actions now properly handles missing original files/a file in the intended path
- Modified some test utility methods for better resilience and easier debugging
- Added a test and fixed other tests
This commit contains code by @nhachicha and @beeender, and replaces https://github.com/realm/realm-object-store/pull/343 and https://github.com/realm/realm-object-store/pull/346
=> Fix issues with metadata and file actions

src/sync/sync_session.cpp, src/sync/sync_session.hpp, tests/sync/session.cpp, tests/util/event_loop.cpp
Changes:
- `SyncSession` now tracks whether the initial sync progress update has happened yet, and manages notifications registered by the binding accordingly
- Session progress notification tests now wait for pending uploads and downloads, to avoid `handle_notifications()` being "spuriously" called by the actual sync client during tests
- Removed use of `check_status()` so we can get useful line numbers should the tests fail
=> Fix an issue with session progress notifications

src/impl/realm_coordinator.cpp, src/schema.hpp, tests/realm.cpp
Make the check stricter (the schema needs to be an exact match and not just compatible), and avoid overwriting the Schema object on the Realm so that pointers to parts of the Schema remain valid.
Fixes #358.
=> Fix schema validation logic when fetching Realm instances from the cache

src/results.cpp, src/results.hpp
This fixes a use-after-free in `is_valid()` when there's nothing else keeping the Table alive after the Realm is invalidated.
=> Store a strong reference to the Table in Results

src/sync/sync_session.cpp, tests/sync/session.cpp
Fixes #292
Any ideas about how to test this change would be greatly appreciated.
=> If a session is dying and receives a fatal error, kill it immediately

src/impl/realm_coordinator.cpp
In the interest of keeping the main code path highly optimised, we will still move `config`, but now source the path of the realm file from the coordinator.
This replaces #364
=> Path from config has been moved, get it from the coordinator's copy

src/sync/sync_session.cpp, src/sync/sync_session.hpp, tests/sync/session.cpp
Changes:
- ~Removed support for 'deferred close'; sessions will immediately close even if waiting for the access token~
- Fixed an issue where the 'deferred close' flag was not properly reset in some cases when transitioning out of 'waiting for token'
- Removed an unused `SyncSession` API
- Added tests to ensure that `SyncSession.close()` works no matter what state the session is in
cc @nhachicha
=> Fix resetting of deferred close flag, and add more sync tests

src/impl/realm_coordinator.cpp, tests/realm.cpp
Realm could be closed in callbacks. If that happened, Realm::refresh()
crashed.
=> Checking realm is_closed in advance_to_latest

src/impl/collection_notifier.cpp, tests/transaction_log_parsing.cpp
Previously it stopped after the first non-null link. It also turned out that the check for exceeding the depth was slightly wrong in a way that was rendered irrelevant by the first bug.
Addresses https://github.com/realm/realm-cocoa/issues/4639.
=> Check all outgoing links for deep change checking

src/impl/collection_change_builder.cpp, src/impl/epoll/external_commit_helper.cpp, src/impl/transact_log_handler.cpp, src/shared_realm.cpp, tests/realm.cpp, tests/transaction_log_parsing.cpp
I think none of these are currently user-visible bugs; most of them are vc++'s iterator debugging identifying things which are invalid but in practice would always happen to work.
=> Fix a pile of issues exposed by building with VC++ 2015

Jenkinsfile, src/sync/sync_manager.cpp, src/sync/sync_manager.hpp, src/sync/sync_session.cpp, src/sync/sync_session.hpp, src/sync/sync_user.cpp, tests/sync/session.cpp
Ownership of a `SyncSession` was previously managed by a `shared_ptr` for as long as there were external references to it. When all external references were dropped and the `SyncSession` became inactive, it was transferred to a `unique_ptr` held by the `SyncManager`. This transfer proved problematic as it meant that the `weak_ptr`s that `SyncSession` used internally to refer to itself from callbacks expired, making it impossible to correctly handle the callbacks.
The new approach is for `SyncSession` to always be managed by a `shared_ptr`. To detect when external references to the `SyncSession` have gone away, we tie the lifetime of the external references to a separate object (by way of `shared_ptr`'s aliasing constructor) and use the destruction of this object to signal that the …
=> Rework the ownership of SyncSession so that it's always managed by a shared_ptr

src/object_accessor.hpp
Since object-accessor is not yet tested in object-store this slipped through the cracks.
Needed because of this change: https://github.com/realm/realm-core/commit/4322f25731a9eb44ae133b0a7a57bb547f83d377
@bdash
=> fix for core 2.3.2 change

tests/util/event_loop.cpp
The condition is now checked every 0.5ms rather than every 50ms. This reduces the time spent within `CFRunLoopRun` during the tests from ~1s to ~20ms. The 0.5ms time was arrived at via trial and error, and produced the lowest overall execution time for the test suite (~1.8s, down from ~4.9s).
=> Shorten the delay between condition checking in CF's EventLoop::run_until

src/sync/sync_session.cpp, src/sync/sync_session.hpp, tests/CMakeLists.txt, tests/results.cpp, tests/sync/session/wait_for_completion.cpp
Changes:
- Completion handlers registered before binding are now queued instead of being silently dropped
To do:
=> Allow completion handlers to be registered before binding

src/collection_notifications.hpp, src/index_set.cpp, src/index_set.hpp, src/object.cpp, src/object.hpp, src/object_accessor.hpp, src/object_schema.cpp, src/object_schema.hpp, tests/CMakeLists.txt, tests/migrations.cpp, tests/object.cpp, tests/transaction_log_parsing.cpp, tests/util/any.hpp, tests/util/test_file.cpp, tests/util/test_file.hpp
The object accessor code was never updated to reflect sync's requirements (no setting the PK after creating objects and default values have to be explicitly flagged for them to be merged correctly).
Quite a bit more is still needed here (this doesn't fully cover the object accessor code and even the parts that are covered aren't particularly thorough), but it's better than nothing.
=> Add basic object accessor tests and fix a few bugs

src/sync/sync_session.cpp, src/sync/sync_session.hpp, tests/sync/session/progress_notifications.cpp, tests/sync/session/session.cpp, tests/sync/session/session_util.hpp, tests/sync/session/wait_for_completion.cpp, tests/util/event_loop.hpp
Fixes https://github.com/realm/realm-object-store/issues/382
To do:
=> Fix issue where non-streaming notifiers were called with stale data

src/shared_realm.cpp, tests/migrations.cpp
`schema` is captured from the enclosing scope by reference, and the only condition in which it's safe to move a value out of it is if the lambda returns `true` (and the enclosing function immediately returns). Otherwise, we attempt to use `schema` afterwards, causing issues since it no longer contains the values we expect.
=> Fix a move-related issue

src/shared_realm.cpp, src/shared_realm.hpp, tests/realm.cpp
Right now we can end up with a realm with a schema referencing non-existent objects which can lead to assertion failures.
@bdash
=> read schema from realm when opening a realm from a custom version

src/object_store.cpp, src/object_store.hpp, src/shared_realm.cpp, tests/migrations.cpp
`schema.compare()` can return a non-empty array and yet still not require a write transaction in Additive mode if all of the differences are that the Realm file has extra columns or index changes that wouldn't be applied anyway due to the schema version not changing.
=> Avoid beginning unnecessary write transactions in Additive schema mode

src/sync/impl/sync_client.hpp, src/sync/sync_manager.cpp, src/sync/sync_manager.hpp, tests/sync/sync_manager.cpp
This PR adds `reconnect()` method to `SyncManager` that forces sync client to reconnect without a delay after connection is back again.
refs https://github.com/realm/realm-object-store/pull/289
/cc @cmelchior, @bdash, @austinzheng, @fealebenpae
=> Add reconnect() method to SyncManager

src/impl/realm_coordinator.cpp, src/impl/realm_coordinator.hpp, src/object_store.cpp, src/object_store.hpp, src/schema.cpp, src/schema.hpp, src/shared_realm.cpp, src/shared_realm.hpp, tests/migrations.cpp, tests/realm.cpp, tests/results.cpp, tests/transaction_log_parsing.cpp, tests/util/test_file.hpp
This attempts to generalize all of the schema handling logic to fully work with the idea that a file's schema may be different at different transaction versions, and different Realm instances may be working with different subsets of the schema at the same time.
RealmCoordinator no longer tries to track "the" schema for a file, and instead has a cache of the most recent schema seen, along with the range of transaction versions that it's known to be valid for. This is used to minimize how often we have to introspect the file, as that's an expensive process.
Opening a Realm with different subsets of tables or columns (in additive or read-only mode) on different threads now fully works. This is mostly for the sake of giving operations sensible semantics: it's unlikely that any of the bindings …
=> Fix a bunch of issues with Realms with non-constant schema

src/shared_realm.cpp, tests/thread_safe_reference.cpp
When resolving a thread safe reference, whose `reference_version` is older than `current_version`, remove config's schema as if that is present, it will advance the read transaction.
Not sure if we need tests for that.
=> Ignore the schema when resolving an older thread safe reference

src/impl/transact_log_handler.cpp, tests/transaction_log_parsing.cpp
Fixes all the `list.col < list.observer->changes.size()` assertion failures.
=> Fix an assertion failure when an observed List is deleted after being modified

src/impl/collection_notifier.hpp, src/list.hpp
Add a move assignment operator to `CollectionNotifier::Handle` that takes a `std::shared_ptr<T>` as Clang 4.0 no longer uses the move assignment operator taking a `Handle` in those cases.
Change `List`'s `m_notifier` member to be a handle to the concerete type rather than the base type, matching what `Results` does.
=> Fix compilation with Clang 4.0

src/sync/impl/sync_metadata.cpp, src/sync/impl/sync_metadata.hpp, src/sync/sync_manager.cpp, src/sync/sync_manager.hpp, src/sync/sync_user.cpp, src/sync/sync_user.hpp, tests/sync/metadata.cpp, tests/sync/sync_manager.cpp, tests/sync/user.cpp
Required for https://github.com/realm/realm-cocoa/pull/4699
Changes:
- Replaced 'is admin' flag with an enum member to distinguish between users that wrap an admin token, and ones that are marked by the server as admins
- Updated user metadata to store the 'is admin' flag
- Updated APIs exposed to bindings to allow a user's admin status to be specified or read out
- Updated tests and user creation code
To do:
=> Properly distinguish between admin users and users wrapping admin tokens

src/impl/realm_coordinator.cpp, tests/results.cpp
https://github.com/realm/realm-cocoa/issues/4768
https://github.com/realm/realm-java/issues/4369
When m_notifiers is empty, m_notifier_sg will be advanced to the latest.
But the skip_version might be behind. In this case, bad_version will be
throw when calling advance_to_final().
=> Fix bad_version when m_notifiers is empty

tests/realm.cpp
Unsurprisingly the test which uses sleep for synchronization is a bit unreliable. Increase how long it sleeps for when running on Android to increase the chance of it working, and ignore failures due to the timing not working out correctly.
Fixed #417.
=> Sleep longer when running Android tests

src/sync/impl/sync_metadata.cpp
`#pragma mark` will cause build errors with `-Wunknown-pragmas`.
=> Use "// MARK:" for code marks

src/list.cpp, src/list.hpp
Currently just a thin wrapper around calling the Results version on the linkview as that was the simplest thing to implement.
=> Add aggregate functions to List

src/impl/realm_coordinator.cpp, tests/results.cpp
advance_to_ready() may be called even if the notifications are for the current version, so it needs to handle that case.
@alazier should fix the GN issue.
=> Fix delivery of notifications for current version when there are later versions

src/impl/collection_notifier.cpp, src/impl/collection_notifier.hpp, tests/transaction_log_parsing.cpp
This is reported by https://github.com/realm/realm-java/issues/4474
The root cause is the nested links is not handled well. In some cases
those indices have been saved to the m_not_modified accidentally.
=> Some link's field changes are not reported

src/sync/impl/apple/system_configuration.cpp
It was my mistake to use `os_log` in https://github.com/realm/realm-object-store/pull/289 because it's not available on all supported versions, reverting it and disabling the deprecation warning for now.
/cc @bdash, @jpsim
=> Revert os_log back to asl_log

src/impl/external_commit_helper.hpp, src/shared_realm.cpp, src/shared_realm.hpp, src/sync/impl/sync_file.cpp, src/util/time.hpp, tests/realm.cpp, tests/util/test_file.cpp
1. Use the `_WIN32` macro to detect building on Windows. This matches what core does, and is consistent with Microsoft's documentation.
2. Test whether `_WIN32` is defined rather than testing its value. Testing its value when its not defined results in a warning with the configuration of some downstream projects.
=> Silence warnings about WIN32 not being defined when building JS binding on Mac

src/sync/sync_config.hpp, src/sync/sync_session.cpp
Changes:
- Set default option so SSL validation is enabled by default
- Code formatting
AFAIK without this change the SSL validation option only defaults to `true` if we use an old version of GCC, which enables the explicitly defined initializer.
=> Set default value for SSL validation option

src/sync/sync_permission.cpp, src/sync/sync_permission.hpp
Changes:
- Permission change timestamps are now set properly
- `realm::Permission` values now expose an `updated_at` property
Note that this PR is based on top of #440 so that I can continue working on the binding, but will be changed to be on top of master if that previous PR is accepted.
=> Add support for `updatedAt` property

src/shared_realm.cpp, src/shared_realm.hpp
The .NET assembly isn't aware if we're running on Windows or other platform, so there's no elegant way to prevent it from calling into those missing methods. Furthermore, the other compact methods are not behind and `#ifndef`, so for consistency's sake, we shouldn't hide these either.
=> Expose the compact api on Win32

src/shared_realm.cpp, tests/realm.cpp
The Cocoa binding stores pointers to `ObjectSchema` instances owned by the `Schema` that the `Realm` instance holds. Replacing the `Schema` invalidates those pointers. To work around the specific issue seen in the Realm Browser we can avoid replacing the schema when it has not changed, which happens whenever new data is written by an external process, whether sync or a different app, while the Browser has a given Realm open. Solving this problem in the face of schema changes will require broader changes (tracked at realm/realm-cocoa#4954).
Related to realm/realm-browser-osx#297 / realm/realm-browser-osx#311.
=> Avoid invalidating object schema pointers when the schema has not changed

src/util/uuid.cpp
Writing size() + 1 bytes into an array does not work.
=> Fix a buffer overflow in uuid_string()

src/sync/impl/sync_client.hpp, src/sync/sync_manager.cpp, src/sync/sync_manager.hpp, src/sync/sync_session.cpp, src/sync/sync_session.hpp
~WIP pending integration with Cocoa changes and manual verification.~ It works
Changes:
- When the reachability system detects network connectivity, the sync manager's `reconnect()` method is now called, rather than directly calling the client cancel delay method.
- The sync manager's `reconnect()` method now asks each session to revive itself if needed.
- If a session is revived in the 'waiting for token' state, the session will now run the login callback. For the Cocoa binding, this simply means that any existing refresh handle will be cancelled and a new one will be created, causing a login request to be sent immediately.
=> Change reconnect logic so sessions are revived upon reconnect

src/sync/sync_permission.cpp, src/sync/sync_permission.hpp
Needs https://github.com/realm/realm-object-server/pull/1137 to work, but shouldn't break anything as is.
Still needs tests in object store (have tests in JS).
=> Object store support for setting permissions by email

CMake/CompilerFlags.cmake
Yields 2x speedup on CI when building for plain Windows (UWP already has `/MP` by default).
=> Parallelize compilation on Windows

src/binding_callback_thread_observer.hpp, src/sync/impl/sync_client.hpp
This is mostly due to the fact that we don't have too much information
when native exception thrown on Android.
With this at least Android has a chance to print the exception message
when error happens on the sync client thread.
=> Let binding be able to handle sync client error

src/shared_realm.cpp, tests/realm.cpp
We need a `Realm` instance in order to perform the compaction, and we likely don't care to perform a compaction if it's not being opened as part of creating a `Realm` instance.
Reported in realm/realm-cocoa#4972.
Needs:
=> Don't attempt to compact on launch if we're opening a Realm file without a Realm instance

src/impl/transact_log_handler.cpp, src/object_schema.cpp, tests/migrations.cpp, tests/schema.cpp, tests/transaction_log_parsing.cpp
This makes it so that the schema handling and notification code doesn't break entirely when given a file with subtable columns. It doesn't make it possible to actually interact with them, but it should be enough to be able to open a file containing them without any issues.
=> Add basic handling for subtable columns

src/impl/object_accessor_impl.hpp, src/object.cpp, src/object.hpp, src/object_accessor.hpp, src/shared_realm.cpp, src/shared_realm.hpp, tests/migrations.cpp
And add some tests for using the object accessor functionality at all inside migration functions.
This takes a different approach from what Cocoa did (just modify the schema to make it so that nothing's a primary key), as that had some unpleasant side effects such that the schema reported to the user inside the migration was wrong, and functionality which required a primary key such as upserting and fetching items by primary key didn't work. This should match the old Cocoa behavior in the key ways, though (PKs can be changed and objects with duplicate PK values can be created as long as there's no duplicates at the end of the migration).
=> Allow changing primary keys inside migrations

src/object_accessor.hpp
`skip_primary` was initialized to the wrong value, so it was never actually skipped. This appears to have not caused any functional problems (I couldn't find a way to write a test that would fail as a result), but it is a small performance hit.
=> Fix double-setting the primary key

src/object_accessor.hpp, src/object_store.cpp, src/sync/sync_features.hpp, tests/object.cpp
This allows us to support sync v1.x and v2.x with the same version of the object store.
The motivation is twofold:
1. Allow bindings to integrate the changes from #434 ahead of being able to switch to v2.x.
2. To allow for the possibility of making objects store fixes for binding version using sync v1.x without having to branch the object store.
Note that this targets the branch for #434.
=> Only use sync's object and table creation APIs if we're using a new enough version of sync

src/sync/impl/sync_metadata.cpp, src/sync/impl/sync_metadata.hpp, src/sync/sync_manager.cpp, src/sync/sync_session.cpp, src/sync/sync_session.hpp, tests/sync/metadata.cpp, tests/sync/session/session.cpp, tests/sync/sync_manager.cpp
Changes:
- 'Permission denied' error now triggers the Realm file to be deleted upon next launch
- Refactored helper method for deleting Realm files
- Added a method for deleting a metadata action directly
- Renamed enum case 'HandleRealmForClientReset' to 'BackUpThenDeleteRealm' to better reflect what it does
Note: the corresponding binding work will introduce a system similar to client reset, allowing users to immediately delete or to keep the Realm file permanently.
=> Add support for deleting Realm upon permission error

src/object_schema.cpp, tests/sync/session/session.cpp
This column is an implementation detail and shouldn't be exposed directly like this.
I noticed this because the column was appearing in Realm Browser. At some point we may want to expose the object ID in the Browser, but I don't think it'll be as a mysterious `__OID` column.
=> Omit sync's __OID column from the schema

CMake/CodeCoverage.cmake, src/util/any.hpp
This improves compile time (159s -> 145s on my machine) and more importantly makes the object files less unreasonably big (1.2 GB total -> 850 MB) which should also reduce the amount of ram needed to link the executable, which has been a problem in the past.
This comes at the cost of making error reporting when unexpected exceptions are thrown significantly worse, but that doesn't really matter for coverage runs.
There's a bunch of other changes from updating from catch 1.7.0 to 1.9.6 but none of them appear to be relevant to us.
=> Build coverage-enabled tests with CATCH_CONFIG_FAST_COMPILE

src/object_store.cpp, tests/migrations.cpp
null migration callback should be treated as same as empty migration
callback in manual mode, throw a SchemaMismatchException if migration
is needed.
=> Check null for migration callback

src/sync/sync_permission.hpp
Very minor preliminary work for https://github.com/realm/realm-cocoa/issues/5076. All the tests for this functionality live in the binding layers right now.
=> Allow permission results to register proper notification blocks

src/sync/impl/sync_file.cpp, tests/sync/file.cpp
The percent encoder encodes some valid UTF-8 bytes as `0xff`. The PR fixes that.
Part of realm/realm-object-server#1267
=> Make the percent encoding function handle characters > 127

src/list.cpp, src/list.hpp
There were various hacky things done to work around the lack of this like sorting by zero columns, so just add the ability to do it directly.
=> Add an explicit conversion from List to Results

src/feature_checks.hpp
This was seen when building realm-js with core v2.8.x.
Core v3.0 renamed `REALM_VER_MAJOR` to `REALM_VERSION_MAJOR`. If the latter isn't defined, we'll #define it to the former so that our version checks see the expected core version value.
=> Silence a warning about REALM_VERSION_MAJOR being undefined

src/impl/realm_coordinator.cpp, src/shared_realm.cpp, src/shared_realm.hpp, tests/realm.cpp
This is a feature for realm-java which has been implemented in java side
before, see https://github.com/realm/realm-java/issues/2254
This gives user possibility to create some initial data only when the
Realm file is created at the first time.
By implementing this in Object Store:
- realm-java can use ResetFile schema mode for
RealmConfigration.deleteIfMigrationNeeded()
- realm-java doesn't have to start a transaction anymore when calling
update_schema().
- in_transaction param of update_schema() can be finally removed from
Object Store.
=> Support for initialization function

tests/CMakeLists.txt, tests/realm.cpp, tests/results.cpp, tests/util/templated_test_case.hpp
Original motivation for this was for writing tests for primitive lists/results, but it also turned out to be useful for refactoring some tests to both be shorter and involve fewer macros.
=> Add support for type-templated test cases

src/impl/results_notifier.cpp, tests/results.cpp
The code assumed that all new rows would be added at the end of the table and so we wouldn't need to handle the case where existing rows are shifted by insertions, but this is no longer the case with sync.
=> Handle non-end insertions in ResultsNotifier

src/sync/impl/sync_file.cpp, src/sync/impl/sync_file.hpp, src/sync/impl/sync_metadata.cpp, src/sync/impl/sync_metadata.hpp, src/sync/sync_manager.cpp, src/sync/sync_manager.hpp, src/sync/sync_session.cpp, src/sync/sync_user.cpp, src/sync/sync_user.hpp, tests/sync/file.cpp, tests/sync/metadata.cpp, tests/sync/session/progress_notifications.cpp, tests/sync/session/session.cpp, tests/sync/session/wait_for_completion.cpp, tests/sync/sync_manager.cpp, tests/sync/sync_test_utils.cpp, tests/sync/sync_test_utils.hpp, tests/sync/user.cpp, tests/util/test_file.cpp
Changes:
- Users are no longer keyed exclusively by user identity, but rather identity and auth URL
- Local copies of synced Realms are now stored in a directory based on a locally assigned UUID, rather than the user identity
- Upgraded tests
TODO:
Fixes #296.
=> Refactor sync user subsystem to support multiple servers

src/list.cpp, src/list.hpp, src/results.cpp, src/results.hpp, src/util/format.cpp, src/util/format.hpp, tests/results.cpp
Mostly just a port of the SortDescriptor building code from Cocoa, since the existing obj-c code doesn't work for primitive arrays and JS (and maybe other bindings) could use this too.
=> Add support for sorting Lists and Results on keypaths

src/binding_context.hpp, src/impl/realm_coordinator.cpp, src/shared_realm.cpp, src/shared_realm.hpp, tests/realm.cpp
There are some difficulties for java binding to hold a pointer to
Realm::schema() and access group though column indices in the Schema
instance, mostly because of performance concerns.
This commit enable a possibility for bindings to know when the Realm
instance's schema gets changed.
- Add schema_changed_function to Realm config.
- schema_changed_function will be called when the schema changes
delivered to the Realm instance to notify binding to refresh the
schema information.
=> Add schema change callback

src/impl/collection_notifier.cpp, src/impl/collection_notifier.hpp, src/impl/transact_log_handler.cpp, tests/results.cpp
CollectionNotifier's cached information about link columns has to be invalidated following a transaction which changes the schema.
Fixes https://github.com/realm/realm-core/issues/2520.
=> Add some missing schema change handling

src/shared_realm.cpp, tests/realm.cpp
Binding needs to see the latest schema in the initialization callback.
=> Update schema before initialization callback

tests/util/templated_test_case.hpp
6225941a318a07e0e501a6e31310682a0ab5747a accidentally undid this fix.
=> Re-fix an off-by-one error in TEMPLATE_TEST_CASE

src/sync/sync_permission.cpp, src/sync/sync_permission.hpp
Allow `realm::Permission` to be used without involving `realm::PermissionResults` at all.
Prerequisite work for https://github.com/realm/realm-cocoa/pull/5168.
=> Allow `realm::Permission` to be constructed from `realm::Results`

src/object_schema.cpp, src/object_store.cpp, src/parser/query_builder.cpp
Property 'CatOwner.cats' has been changed from `array` to
`array`."
->
Property 'CatOwner.cats' has been changed from `array<Dog>` to
`array<Cat>`."
=> Better message to show the mismatched schema

src/impl/collection_notifier.cpp, src/impl/collection_notifier.hpp, tests/transaction_log_parsing.cpp
16 was a completely arbitrary choice to begin with, and has turned out to be too large to actually avoid problems in pathological cases. This doesn't fix the problems with strongly-connected object graphs, but should do a better job of mitigating them until we have time for a proper solution.
This is arguably a breaking change? The limit isn't something we've ever documented so maybe it doesn't really count. In practice the people who actually want changes to linked objects reported seem to usually only want it one level deep anyway.
=> Lower the maximum search distance for changes from 16 to 4

src/impl/realm_coordinator.cpp, src/object_store.cpp, src/object_store.hpp, src/results.cpp, src/shared_realm.cpp, src/shared_realm.hpp, tests/migrations.cpp, tests/realm.cpp
realm-java has a different semantics of read-only mode. In realm-java,
there is no limitation that the read-only Realm won't be changed by
sync or by the other process. realm-java only has a restriction that
user cannot apply write transactions on the read-only Realm instance.
=> Add ReadOnlyAlternative SchemaMode

src/impl/object_accessor_impl.hpp, src/list.hpp, src/object_accessor.hpp, tests/object.cpp
Doing this purely at the binding level misses the places where the assignment doesn't happen via the binding code.
=> Make List property self=assignment a no-op

src/sync/sync_config.hpp, src/sync/sync_session.cpp
following the work on Sync repo https://github.com/realm/realm-sync/pull/1312 to allow the binding to pass a callback to validate the SSL certificate, this PR expose this option to the binding so we can set the callback when building the `SyncConf`
Will be used mainly for Java to allow Android trust manager to validate  the cert https://github.com/realm/realm-java/issues/4759
=> add support to ssl_verify_callback option

src/list.cpp, src/shared_realm.cpp, tests/thread_safe_reference.cpp
Fixes #528. Turns out we didn't actually have objectstore tests for this.
=> Fix crashes when deleted objects are imported from handover

src/sync/sync_manager.cpp
This assertion attacked realm-java integration tests a lot.
And realm-java cannot enable assertion for CI build due to the speed
issues, this assertion is kind of turned into many ways of native
crashes for realm-java CI.
Change it to a release assertion so realm-java can crash earlier.
=> Use release assertion in reset_for_testing

src/list.cpp, src/list.hpp, tests/list.cpp
`List` has `delete_all()` to delete all target objects, but does not have a method to delete single target object in `List`
This PR adds `List.delete_at(size_t)` to achieve that.
=> Add List::delete_at(size_t)

src/object.cpp, tests/object.cpp
Without this check it hits an assertion failure rather than throwing a useful error.
Reported by https://secure.helpscout.net/conversation/433478799/11309/
=> Add a missing check for deleted objects in add_notification_callback()

src/list.cpp
This threw a pointlessly different exception from other write transaction checks that made things a little awkward to test.
=> Simplify List::verify_in_transaction()

tests/CMakeLists.txt, tests/sync/session/session.cpp
When building the project in Xcode, the tests binary ends up at `tests/Debug/tests` but the realm file was being copied to `tests/sync-1.x.realm`, so it failed to find the file. The copy needs to be done at build time rather than configure time to support build systems which support multiple configurations.
=> Copy sync-1.x.realm to the correct place when building in Xcode

src/sync/sync_permission.cpp, src/sync/sync_permission.hpp
This accomplishes a few things:
- Prevents ROS from complaining
- Allows us to leverage the object store level permissions code in the future to implement permission offer/response at this layer
=> Add model definitions for PermissionOffer and PermissionOfferResponse

src/sync/sync_permission.cpp, src/sync/sync_permission.hpp
Changes:
- Added APIs for creating permission offers and accepting them
- Refactored some code to facilitate reuse
- Renamed a few types to reflect their new, expanded usage
Rationale: right now, most bindings (Cocoa included) use the object store APIs to get and change permissions, but binding-level APIs to create and accept permission offers. This API allows the existing object store machinery to be used to perform the latter task as well.
More detailed description.
1. I broke most of the existing method for changing permissions into a new method, `perform_async_operation()`. This method basically creates an object, writes it to the management Realm, and observes it until its status code indicates either success or failure. Then it calls a callback.
2. Changing permissions, creating …
=> Add support for permission offer/response

src/sync/sync_config.hpp, tests/sync/session/session.cpp
Always use the `SyncConfig` constructor. It removes the potential for inconsistent initialization between the constructor and braced initializers. In addition, the default constructor is removed as it doesn't result in a meaningful `SyncConfig`.
At some point soon we should reevaluate how `SyncConfig` is used. It was initially intended to contain only two or three values, but has grown to over ten ☹️
=> Fix SyncConfig initialization to be consistent between Clang and GCC >= 5

src/sync/sync_session.cpp
Fixes https://github.com/realm/realm-sync/issues/1691
If an Object Store Session becomes active and the user then enables airplane mode (e.g. to demo Sync), then the Sync layer correctly detects this and starts using incremental backoff, but Object Store Session stays in `Active` mode.
This is a problem as `SyncManager::reconnect()` doesn't have any effect when a binding detects that network comes back.
This PR changes it, so it is now possible to cancel the reconnect delay even when the session is considered active from the point of view of Object Store.
=> Fix reconnect not happening correctly in some network situations.

src/feature_checks.hpp, src/sync/sync_session.cpp, src/sync/sync_session.hpp
We test only the major version as there's no easy way to distinguish between 2.0.0 and previous release candidates.
This addresses post-merge feedback that was given on #568.
=> Express the guards around override_session in terms of the sync version

src/sync/impl/sync_metadata.cpp
#572 will provide a fix for users who have already encountered this bug.
Fixes #569
=> Fix improper migration of sync metadata keychain item

src/impl/collection_notifier.cpp, src/impl/collection_notifier.hpp, tests/results.cpp
The previous behavior of sending the initial notification immediately would result in notifications being lost if the background worker ran at exactly the wrong time. Fixing this turned out to be complicated and sending the initial notification immediately was inconsistent with the normal behavior, so just don't.
The newly added test is a simplification of what the java permissions code is doing that results in https://github.com/realm/realm-java/issues/5413, and without these changes is called once with `table->get_int(0, 0) == 0`, and then is not called again when the realm is advanced to the version with it set to 5.
=> Defer delivery of the initial notification when a callback is added from within a callback on the same collection

src/sync/sync_manager.cpp
This doesn't affect Cocoa. Not sure about other bindings. Still needs to be fixed.
=> Fix use-after-move error

src/impl/realm_coordinator.cpp, src/index_set.cpp
`clang-tidy` uncovered a few issues.
=> Fix some use-after-move errors

src/sync/sync_permission.cpp
It seems these are somewhat more serious than those from #577. Without these fixes, a user's internal permissions and management Realms will continue syncing even if the user logs out.
=> Fix two use-after-move issues flagged in sync-related code

src/collection_notifications.cpp, src/collection_notifications.hpp, src/impl/collection_notifier.cpp, src/impl/collection_notifier.hpp, tests/results.cpp
Reusing notifier tokens resulted in deregistering a token created before errors were delivered actually removing a callback registered after errors were delivered.
Unlikely that this has ever actually been a problem for anyone, but there's really no reason to be reusing tokens and this makes the code simpler.
=> Fix an edge case that would result in errors not being delivered

src/object_store.cpp, src/object_store.hpp
- Use constexpr for NotVersioned which is easier for java to do
static_assert check.
- Remove FIXME for ObjectStore::set_schema_version. It is still useful
for realm-java after switching to use Object Store schema:
- It is useful for constructing schema related test cases.
- It is used to create meta tables for realm-java's dynamic Realm.
=> Use constexpr for NotVersioned

src/impl/collection_notifier.cpp, src/impl/collection_notifier.hpp, tests/results.cpp
The initial notification for callbacks added within a callback for a *different* collection also need to be deferred for the same reason as when it's the same collection.
=> Fix more problems with adding callbacks from within callbacks

src/sync/impl/sync_client.hpp, src/sync/sync_manager.cpp, src/sync/sync_manager.hpp, src/sync/sync_session.cpp
This is disabled by default as it doesn't work with load balancing, but the GN really needs it.
Since the option to disable multiplexing was originally just there for tests the API for this is pretty awkward, but we can sort that out later.
I'm not really sure how to usefully test this at the objectstore layer, but I have verified that it achieves the desired end result (by calling this function the GN is able to open >10k realms rather than hitting the open file limit at 1500).
=> Expose an option to enable sync multiplexing

src/sync/sync_config.hpp, src/sync/sync_session.cpp, tests/sync/session/session.cpp, tests/sync/session/session_util.hpp, tests/sync/sync_manager.cpp, tests/util/test_file.cpp, tests/util/test_file.hpp
Changes:
- SyncConfig's constructor only takes the two required arguments now; all others must be explicitly set
- SyncConfig now throws an exception if the URL passed in is invalid
- Fixed a broken test case
Fixes #579
=> Improve sync config

src/impl/collection_notifier.cpp
The tracking of which rows *aren't* modified (to avoid rechecking if a row has multiple incoming links) ends up being a sizeable portion of the runtime in this case (~25% in the case that I happened to profile) and is completely pointless, so just skip it.
=> Skip deep change checking for tables with no outgoing links

src/impl/realm_coordinator.cpp
If it doesn't already exist.
The global notifier opens and then immediately closes each Realm during startup
purely for the sake of creating the sync session (it used to do more with the
Realms, but hasn't for a long time), and with a large number of Realms this
starts to take a significant amount of time.
=> Create the sync session in set_transaction_callback()

Jenkinsfile
Our windows nodes on CI come with a number of Windows SDKs and CMake has trouble selecting the right one.
=> [CI] Explicitly select Windows SDK

src/sync/sync_session.cpp, tests/sync/session/session.cpp
This is needed to support reviving an admin token user's session, since this is called instead of revive_if_needed().
Fixes https://github.com/realm/realm-js-private/issues/375.
=> Implement sync_session_state::Dying::bind_with_admin_token()

.gitignore, src/sync/sync_config.hpp, src/sync/sync_session.cpp
The sync error handler was silently ignoring unrecognized errors. This change flags such errors as unrecognized and passes them to bindings, giving bindings the option to handle them further (e.g. present them to users).
=> Don't ignore unrecognized sync errors

src/results.cpp, src/results.hpp
The orignal purpose of not creating TableView in size() is to make the
call faster if the query has not been executed before. But in the real
usecases, users always try to call accessors after the size() which
makes the query gets executed twice. See java issue
https://github.com/realm/realm-java/issues/5328
https://github.com/realm/realm-java/issues/5387
With this change, there would be no difference if the query has been
evaluated before.
It will be faster if:
- Calling Results::size() multiple times in the same event loop.
- Calling any accessors after Results::size().
It will be slower if:
- Calling Results::size() at the first time.
=> rename update_tableview to evaluate_query_if_needed and expose it to public

src/sync/sync_session.cpp, src/sync/sync_session.hpp
Used by https://github.com/realm/realm-js/pull/1499 to make the GN work with multiple backend shards.
I don't think there's any meaningful way to test this at the objectstore level.
=> Expose the ability to set the multiplex identity

src/sync/sync_config.hpp, tests/sync/session/session.cpp
Add a constructor to `SyncError` since GCC 4.9 doesn't like brace initialization with non-static data member initializers.
=> Fix the build with GCC 4.9

src/list.cpp, tests/list.cpp
If a transaction is processed while a notifier has no callbacks, no work is done for that notifier and it gets into an inconsistent state. Adding a new callback to that notifier thus results in incorrect results from the first notification sent due to that the cached state is not properly reinitialized. Work around this for now by just not reusing list notifiers.
This problem does not apply to Results notifiers due to that the changeset in the Initial notification for those is not meaningful.
Fixes #601.
=>  Don't reuse list notifiers which had all callbacks removed

src/sync/sync_permission.cpp
Necessary to upgrade Cocoa dependency to 2.1.0 without adding test workarounds. (This third implementation detail Realm was added at some point between 2.0.13 and 2.1.0, and needs to be excluded in order to hide extraneous results.)
=> Exclude `__perm` internal Realm from permission results

src/sync/sync_session.cpp, src/sync/sync_session.hpp, tests/sync/session/progress_notifications.cpp, tests/sync/session/session.cpp, tests/sync/session/wait_for_completion.cpp
Fixes one part of realm/realm-sync#1857. An alternative, more invasive, approach to #613.
=> Remove SyncSession's Error state entirely

src/util/generic/event_loop_signal.cpp, src/util/generic/event_loop_signal.hpp
This is a much nicer event loop abstraction that allows us to not be forced to use opaque pointers or rely on extern DATA symbols.
Functionality in realm-dotnet-server relies on this.
=> Enhance GenericEventLoop abstraction

src/sync/impl/sync_file.cpp
UWP lacks POSIX compatibility. Fortunately, the CRT has similar functions.
=> Don't use POSIX on Windows

src/impl/realm_coordinator.cpp, src/sync/sync_session.cpp, src/sync/sync_session.hpp
This removes the need to go through RealmCoordinator to set the error handler and is just generally simpler with seemingly no downside.
=> Use the error handler from the config in SyncSession

src/sync/sync_session.cpp, src/sync/sync_session.hpp, src/sync/sync_user.cpp
When session multiplexing is enabled we need to perform a token refresh even with admin token users so that ROS knows that we're accessing a new Realm (as it can't just automatically detect that from the fact that we've opened a new connection).
All bindings need to be updated to support this, but bindings which do not support multiplexing (i.e. everything but JS) can simply "refresh" the token on the session without talking to the server. Cocoa doesn't support admin token users at all, so it doesn't need any updates.
Object store part of the fix for https://github.com/realm/realm-object-server-private/issues/836.
=> Remove bind_with_admin_token() and use the normal refresh flow

src/sync/sync_session.cpp, src/sync/sync_session.hpp, tests/sync/session/progress_notifications.cpp
When a non-streaming progress notification is added immediately after a local commit was made, that progress notification could capture the total bytes to upload before that value was actually updated to reflect the newly made transaction, resulting in the notifier completing before the upload actually happened. Fix this by tracking the last seen local transaction version and only capture the uploadable bytes value once the sync progress is for that version or later.
The functional changes are all in the second commit. The first commit extracts the callback management code to a helper class that can be unit tested directly rather than via test helper functions on SyncSession (none of the existing tests were integration tests that meaningfully tested it by doing things via sync).
Fixes …
=> Fix upload progress reporting

src/results.cpp, src/results.hpp, tests/results.cpp
This is a more generic method which will help the js binding easily integrate the parsed sort/distinct descriptors.
=> Add an `apply_ordering` method to `Results`

src/sync/sync_manager.cpp, src/sync/sync_manager.hpp
This removes the need to open and access a Realm file from within `SyncManager::client_uuid()`, which was problematic as it can be called in the process of opening a Realm file. This is both surprising, and had the potential to cause a deadlock on some platforms.
This fixes the hang I was hitting in #628.
=> Fetch the client's UUID when configuring the SyncManager's file system support

src/CMakeLists.txt, src/impl/realm_coordinator.cpp, src/impl/realm_coordinator.hpp, src/object_store.cpp, src/object_store.hpp, src/shared_realm.cpp, src/shared_realm.hpp, src/sync/impl/work_queue.cpp, src/sync/impl/work_queue.hpp, src/sync/partial_sync.cpp, src/sync/partial_sync.hpp, src/sync/subscription_state.hpp, src/sync/sync_manager.cpp, src/sync/sync_session.hpp, tests/sync/partial_sync.cpp
This replaces the partial sync API introduced in #547 with one that supports named queries, and that allows subscribing to an existing `Results` so bindings can build queries using their high-level APIs. It supersedes @cmelchior's PR in #610 based on discussions on Slack about the difficulty of adapting that implementation to Cocoa's API.
Not yet supported:
Remaining work needed here:
Things to further evaluate:
I'm flagging this for review despite their being some work remaining so I can start getting feedback.
=> Replace the partial sync API

src/sync/partial_sync.cpp, tests/sync/partial_sync.cpp
The description of sort/distinct needs to be serialised from the descriptor orderings that are stored in the Results class.
The strange thing is that the added test actually works with the changes commented out. Am I missing something here? How can I test this change?
=> Testing that sort/distinct orderings are applied to partial sync

src/shared_realm.cpp, src/shared_realm.hpp, tests/sync/permission.cpp
PermissionsCache can return values with unused bits set. This is normally harmless, but it has confusing results when the bitmask is dumped into a Swift OptionSet.
=> Mask off extra bits set in computed privileges

src/object.cpp, src/object.hpp, src/object_accessor.hpp, tests/sync/permission.cpp
Special-casing a single type like this is pretty gross, but doing it at higher layers wasn't really any better, and making it easy to accidentally have users that aren't a member of "everyone" is a pretty big footgun.
=> Make it difficult to create permission Users not in the "everyone" role

src/impl/realm_coordinator.cpp, src/impl/transact_log_handler.cpp, tests/realm.cpp
#634 added some more places where Realms can be closed while we're in the middle of doing things and need to exit early if so.
=> Fix crashes when a Realm is closed from within a notification callback

src/impl/transact_log_handler.cpp, src/impl/transact_log_handler.hpp, src/object_store.cpp, src/object_store.hpp, src/schema.cpp, src/schema.hpp, src/shared_realm.cpp, src/shared_realm.hpp, tests/schema.cpp, tests/sync/permission.cpp
Add in a description of what the incompatible schema changes were along with a note that this is probably happening due to a lack of permissions so that users will hopefully have some idea of what they need to do to resolve the problem.
=> Improve error reporting when the server reverts schema changes

src/shared_realm.cpp, src/sync/impl/sync_metadata.cpp, src/sync/impl/sync_metadata.hpp
A customer using partial sync and thread-safe references with .NET on Android reported a deadlock in a peculiar scenario.
Basically he had a partial realm where he was writing objects that didn't match any of the subscriptions and so the server was deleting them from the partial realm.
On Linux (and Android) this causes a lot of churn in `ExternalCommitHelper` because of the constant opening and closing of realms due to `GetInstance` and `ResolveReference` calls coupled with the sync client integrating frequent changesets. This apparently causes `ExternalCommitHelper::DaemonThread::m_mutex` to deadlock.
The solution is to disable automatic change notifications for realms that don't need them so that `ExternalCommitHelper` instances don't get created needlessly.
The .NET reproduction …
=> Disable change notifications for internal transient realms

src/sync/sync_session.cpp, src/sync/sync_session.hpp
Doing so produces a deadlock if the callbacks attempt to interact with the session, or release the last strong pointer to the session.
=> Don't call session completion callbacks while holding the state mutex

.gitmodules
No particularly interesting changes between 1.09 and 1.12, but they moved the repo URL so it'd be good to point it at the correct place.
=> Update catch to 1.12

src/impl/results_notifier.cpp, src/results.cpp, src/results.hpp
See https://github.com/realm/realm-cocoa/issues/5816. This fixes the problem in two ways: it skips implicitly creating a notifier at all for LinkingObjects, and skips calculating the change sets for Results which do need a background notifier but don't have any callbacks.
No new tests as this should have no functional impact other than being faster. The obj-c tests do attempt to verify that the implicit notifier is created in the places where we actually want it (and those tests still pass).
=> Skip some pointless background work for LinkingObjects notifiers

src/shared_realm.cpp
Since we do the optimisation in a read transaction and never commit, it's wasted cpu cycles. LOL.
We were going to put this in a write transaction (https://github.com/realm/realm-object-store/pull/501 ) but we never got the go ahead because we kept finding problems in the enum columns by fuzz testing.  I think we decided to just enable them in core 6 so that they didn't have to be upgraded from 5->6.
=> Speed up compact

src/impl/realm_coordinator.cpp, src/impl/realm_coordinator.hpp, src/shared_realm.cpp, src/shared_realm.hpp, tests/realm.cpp
- current_transaction_version
- enable_wait_for_change
- wait_for_change
- wait_for_change_release
realm-java was asking for this.
=> Implementing a few missing operations on Realm

src/sync/impl/sync_file.cpp, src/sync/impl/sync_file.hpp, src/sync/sync_manager.cpp, tests/sync/file.cpp
It's unclear what this file was intended to be used for (the comments just say "for backup purposes"), and I can't find any evidence that anything other than the test has ever actually read the file.
Fixes #680.
=> Don't create the __user_info file

src/results.cpp, tests/results.cpp
It seems that notifications for limited query results "just work" so re-enabling them and adding a smoke test.
=> Enable notifications for limited query results

src/sync/sync_config.cpp
This does silly things to remain compatible with older versions as well in case we do end up needing to make new releases with the old protocol version.
=> Fix compilation with sync 3.11.1

src/object_store.cpp, src/shared_realm.cpp, src/sync/partial_sync.cpp, src/sync/partial_sync.hpp, tests/sync/partial_sync.cpp
* This adds the capability of creating subscriptions immediately by using `subscribe_blocking()`. This is required by new additions to Java. 
* Removed old methods that were only used by Java, but are no longer relevant.
* Added support for specifying the __ResultSets class in the users Schema. This fixes: https://github.com/realm/realm-object-store/pull/698
TODO
=> Add support for creating a subscription object immediately

src/collection_notifications.hpp
This resulted in the destructor for the callback object passed to `add_notification_callback()` not being called, potentially resulting in memory leaks when removing notification callbacks.
=> Add a missing virtual destructor to CollectionChangeCallback

src/impl/object_accessor_impl.hpp, src/list.hpp, src/object.hpp, src/object_accessor.hpp, src/results.hpp, tests/object.cpp
Lists will be compared if the length is preserved - otherwise rewritten.
Objects with primary key will always just be updated if they already exist in the database.
In the case of single link to object without primary key we compare each value individually.
Lists of objects without primary key wil not yet be compared.
=> Initial implementation of diff-only update of objects

src/sync/partial_sync.cpp, src/sync/partial_sync.hpp
This returned the list of objects matching the subscription which used to be populated by the server, but no longer is and now is just always empty.
=> Remove Subscription::results()

src/sync/sync_manager.cpp, src/sync/sync_manager.hpp
It turned out that setting both the binding and application user-agent info in `configure` wasn't optimal for how JS uses ObjectStore, so in this refactor I split the two parts. The binding level info is still configured when calling `configure` as it doesn't involve user input. The application level info now has a method similar to how `set_log_level` works.
=> Support setting binding/application user agent

src/shared_realm.cpp, src/shared_realm.hpp
3.13.3 made it so that we have to construct the TableInfoCache ourselves and pass in a reference to the PermissionsCache.
=> Fix compilation with sync 3.13.3

src/sync/partial_sync.cpp, src/sync/partial_sync.hpp, tests/sync/partial_sync.cpp
Needed for https://github.com/realm/realm-cocoa/pull/6029.
=> Allow unsubscribing from a query without a Subscription

tests/sync/permission.cpp
3.14 added a new property to the __ResultSets table and a few of the tests use an object schema read from the table, so object creation in those tests now require a value for that property. Supplying a value for a property that doesn't exist is harmless, so there's no need to make this conditional.
=> Fix running the tests with sync 3.14

src/impl/realm_coordinator.cpp, src/shared_realm.cpp, tests/results.cpp
The root cause of https://github.com/realm/data-adapters/issues/464
The adapter vends Realm instances to the user code which have automatic change notifications disabled (they wouldn't really work properly with how the adapter integrates into things and disabling them cuts resource usage), but holds on to a long-lived RealmCoordinator for each adapted Realm. If the user code queried one of these Realms we'd implicitly create a ResultsNotifier for the results which pins the current transaction version, which would then never be cleaned up since the worker thread isn't running.
This fixes both of the problems there: if we aren't using the notification worker thread we shouldn't implicitly create notifiers, and if the user explicitly creates a notifier we should clean it up when the Realm is …
=> Avoid pinning Realm versions when queries are made with automatic change notifications disabled

src/sync/sync_manager.cpp
When session multiplexing is already enabled, we shouldn't throw, even if the sync client has already been created.
=> enableSessionMultiplexing should not throw when enabled

src/sync/sync_manager.cpp, src/sync/sync_manager.hpp, tests/sync/sync_manager.cpp
Add helper method that checks if the SyncManager holds any sessions.
The primary use case is cleaning up tests.
We don't seem to have a consistent paradigm for isolating private logic that needs to be guarded by a mutex when called from the public API. It appears that Core heavily uses the `do_xxx` prefix to indicate the unguarded private method and just `xxx` for the public method. So I adopted the same pattern.
=> Add has_existing_sessions()

CMakeLists.txt, external/json/json.hpp, src/CMakeLists.txt, src/server/adapter.cpp, src/server/adapter.hpp, src/server/admin_realm.cpp, src/server/admin_realm.hpp, src/server/global_notifier.cpp, src/server/global_notifier.hpp, src/sync/sync_manager.cpp, src/sync/sync_manager.hpp, src/util/event_loop_dispatcher.hpp, tests/sync/sync_manager.cpp, workflow/build.sh
The first step for https://github.com/realm/realm-js-private/issues/462 and https://github.com/realm/realm-dotnet-server/issues/4.
This is just the six cpp/hpp files sliced out of realm-js-private and imported here with zero changes as reviewing those changes would be awkward. The next step after this will be to add build system support so that these files are at least compiled and to move the JS/node-specific portions of the GN and adapter to realm-js.
=> Import the global notifier and adapter from realm-js-private

src/sync/partial_sync.cpp, src/sync/partial_sync.hpp, tests/sync/partial_sync.cpp
It turned out I forgot to reset the status flag when updating a subscription which meant the server never re-evaluated the query. This PR fixes that.
Also, it turned out there was a bunch of race conditions in the subscription notifications. This PR also fixes the following issues:
- The same subscription being reported twice.
- `Invalidated` is now being reported even if the subscription is deleting manually. Previously it was only reported if you used the explicit unsubscribe API.
TODO
=> Reset status flag when updating subscription

src/sync/partial_sync.cpp, tests/sync/partial_sync.cpp
Unsubscribing from a Subscription which was still in the Creating state only worked correctly if the caller held onto a reference to the Subscription object until it made it to the Invalidated state (as the existing tests happen to). If it was destroyed we would either fail to remove the subscription or even outright crash depending on when the Subscription object was deallocated.
Fixes https://github.com/realm/realm-js-private/issues/520.
=> Fix unsubscribing from a subscription which hasn't been created yet

src/object.hpp, src/object_accessor.hpp, src/object_schema.cpp, src/object_schema.hpp, src/property.hpp, src/schema.cpp, tests/schema.cpp
In order to avoid breaking changes in JS (see https://github.com/realm/realm-js/issues/2266), we need to have support for re-mapping fields in the JS schema. This feature is already present in Java, Cocoa and the core query engine, so this PR just adds the tempory data to the schema objects in Object Store similar to computed properties. 
**Usage in bindings**
Bindings are responsible for setting and using the alias field.
Reading/Writing fields are supported by overriding the `Object::value_for_property` method in the Object Accessor. 
Queries support this by creating a specific `KeyPathMapping` with the alias fields.
See https://github.com/realm/realm-js/pull/2306 for an example on how this is used.
**Performance considerations:**
A few comments about performance impact:
We don't …
=> Add support for field aliases to properties 

src/sync/impl/sync_metadata.cpp, src/sync/impl/sync_metadata.hpp, src/sync/sync_session.cpp, tests/sync/metadata.cpp, tests/sync/sync_manager.cpp
Fixes https://github.com/realm/raas/issues/1539.
The core fix here is to use `Realm::open_with_config()` rather than `Realm::get_shared_realm()` in `make_file_action_metadata()` to avoid creating an `EventLoopSignal` instance, as that function is called from the sync worker thread when a client reset error occurs, and the libuv implementation of `EventLoopSignal` can only be constructed on the main thread.
The other changes are related to that the tests relied on `make_file_action_metadata()` reusing the cached Realm instance which they already held on to. This shouldn't be an issue for non-test code as these functions are mostly all internal to objectstore and not things that the SDKs call directly.
=> Avoid creating Realm instances on the sync worker thread

src/shared_realm.cpp
Needed for https://github.com/realm/realm-js/pull/2373 since that results in `clearTestState()` being called while processing the before_notify() handler, which closes the realm.
=> Recheck if the realm is closed after before_notify()

src/list.hpp, src/object_accessor.hpp, tests/object.cpp
`table.get<int64_t>()` and friends don't work on nullable int properties and would hit an assertion failure. Fix this by switching to using `switch_on_type()` which dispatches to `Optional<T>` where applicable.
=> Fix using update_only_diff on nullable primitive properties

src/impl/realm_coordinator.cpp, tests/realm.cpp
It isn't yet implemented on the server for query-based sync and produces a sync error.
Fixes https://github.com/realm/realm-cocoa/issues/6178.
=> Only use state transfer for async open on full sync Realms

src/impl/apple/external_commit_helper.cpp
We just want to re-call kevent when it happens. The epoll version already did this.
Might be the cause of https://github.com/realm/realm-cocoa/issues/6144 or might be unrelated.
=> Handle EINTR in the apple version of ExternalCommitHelper

src/impl/realm_coordinator.cpp, src/impl/realm_coordinator.hpp, src/impl/weak_realm_notifier.cpp, src/impl/weak_realm_notifier.hpp, src/shared_realm.cpp, src/shared_realm.hpp, src/sync/async_open_task.cpp, src/sync/async_open_task.hpp, src/sync/impl/sync_file.cpp, src/sync/impl/sync_file.hpp, src/sync/partial_sync.cpp, src/sync/partial_sync.hpp, src/sync/sync_session.cpp, src/thread_safe_reference.hpp, src/util/event_loop_dispatcher.hpp, tests/realm.cpp, tests/sync/permission.cpp, tests/sync/session/session.cpp
This includes changes needed to get the realm-js and realm-cocoa tests passing using the new async open, and fixes a bug which hits Cocoa which wasn't caught by those tests.
AsyncOpenTask now takes more control over its lifetime: the callback holds a strong reference to the task until it's called so that retaining the AsyncOpenTask externally is optional, and cleans itself up after calling the callback passed to `start()` so that the SDK code doesn't have to worry about that. Some thread-safety problems around using `m_session` from multiple threads have been fixed by using `AtomicSharedPtr<>`, and calling `cancel()` while it happens to be processing the callback will no longer crash.
The state dir for async open/resync is now a directory named after the Realm rather than a single shared …
=> Fix some async open issues

src/shared_realm.cpp
[cache_new_realm](https://github.com/realm/realm-object-store/blob/master/src/shared_realm.cpp#L574-L577) used to check if the shared_group is still open/valid before proceeding to read the current transaction version id. In Core 6 this checks [is not done](https://github.com/realm/realm-object-store/blob/core-6/src/shared_realm.cpp#L430-L432), which causes the call to `transaction()` to throw. (`transaction()` -> `read_group()` -> `verify_open()` -> Throw `ClosedRealmException`). This PR adds the check to return quickly if the Realm was closed.
=> Adding check for cache_new_realm

src/sync/partial_sync.cpp
Table::size() is not the number of columns in the table.
This probably worked out okay in practice because it "works" as long as the user creates at least 4 subscriptions, but until they do it resulted in a bunch of extra empty write transactions.
=> Fix the check for if the ResultSets schema needs to be initialized

src/sync/sync_config.hpp, src/sync/sync_session.cpp, src/sync/sync_session.hpp
On Cloud we're doing away with the Sync Proxy. Previously sync clients would open websockets pointing to `my-awesome-instance.us1.cloud.realm.io/realm-sync/url-encoded-realm-path` and the server-side routing to different sync workers was done by the Sync Proxy sitting on the `/realm-sync` endpoint - it would inspect an incoming request, determine where to proxy it, and open another socket to do so.
We're adding a new mechanism that bypasses proxying and instead exposes every sync worker for an instance on a public path like `/sync/{worker-name}` so it would be possible for the client to make a request to `/sync/alpha/url-encoded-realm-path` and connect directly to the sync worker.
To this end token refresh responses by Cloud will now include the URL path of the sync worker in question …
=> Allows changing url_prefix of a created sync session

src/sync/sync_config.hpp
It follows the pattern of similar enums and also makes the size predictable when marshalling the structure between layers (e.g. .NET <-> C).
=> Make ClientResyncMode an unsigned char

src/impl/primitive_list_notifier.cpp, tests/list.cpp, tests/primitive_list.cpp
For version management reasons, the first run of a notifier is done on a different SharedGroup from all of the subsequent runs. This requires detaching the notifier from the first SG and attaching it to the second one by handing over the Table. This doesn't work if the Table was deleted, so we need to explicitly handle that case.
Fixes https://github.com/realm/realm-cocoa/issues/6234.
=> Fix a crash when an observed primitive list is deleted before the first run of the notifier

src/impl/realm_coordinator.cpp
This adds a required work-around for https://github.com/realm/realm-java/issues/6619
Unit tests are found in Java PR (https://github.com/realm/realm-java/pull/6621)
=> Add work-around for Java schema bug

Jenkinsfile
Catch2 was released this weekend with a workaround for old compilers (aka our ancient android ndk r10e) missing support for `std::nextafter` by using a config `CATCH_CONFIG_GLOBAL_NEXTAFTER`. The release just means we no longer have to manually generate the header file.
[Release notes.](https://github.com/catchorg/Catch2/blob/master/docs/release-notes.md#2100)
=> Upgrade Catch2 to 2.10.0

tests/CMakeLists.txt, tests/benchmarks/CMakeLists.txt, tests/benchmarks/main.cpp, tests/benchmarks/object.cpp, tests/benchmarks/results.cpp
This is mostly to set up the benchmarking framework with some examples.
Although Catch2 supports intermixing benchmarks and unit tests, I chose to separate out the benchmarks into a different target. This separation means no increase in compile times for the unit tests, and no mixed output between tests and benchmarks.
The benchmark documentation is [here](https://github.com/catchorg/Catch2/blob/master/docs/benchmarks.md#top)
=> Add some basic benchmarks

src/impl/realm_coordinator.cpp, src/impl/realm_coordinator.hpp
Adding some public functionality for creating sessions before the Realm is opened.
Due to how Java has implemented Async Open and how the Java APIs are, we have a hard time using the OS AsyncOpenTask for download progress listeners. 
Instead, we need to use our SyncSession wrapper which previously was only available after the Realm was fully opened. So by making this change, we are able to create the wrapper before the Realm is opened and allow users to add progress listeners for async open.
=> Add support for creating a sync session manually

src/impl/realm_coordinator.cpp
The following sequence of events would hang forever:
1. Main thread creates notifier and adds callback.
2. Background thread performs a write.
3. Main thread calls refresh() and waits on the notifier condition variable.
4. Background thread removes callback.
5. Notification worker thread wakes up, cleans up the zombie notifier, then returns since there's no notifications to run.
6. Main thread blocks forever because no one ever signals the notifier condition variable.
The fix for this is to just signal the condition variable even if there are no live notifiers.
I *think* this is what has been causing the Cocoa sync tests to sometimes hang forever on CI. It's unlikely that any actual users have hit it, as the problematic timing window is pretty tight and you have to do somewhat weird …
=> Fix a rare notification-related deadlock

src/impl/object_accessor_impl.hpp, src/list.hpp, src/object.hpp, src/object_accessor.hpp, src/results.hpp, src/sync/sync_permission.cpp, tests/migrations.cpp, tests/object.cpp, tests/sync/metadata.cpp, tests/sync/permission.cpp
Calling Object::create(update_only_diff=true) on an object type which had a List of objects would fail to propagate update_only_diff=true to the sub-calls of Object::create(), resulting it those objects not being diffed and incorrect change notifications being generated.
Because passing around 3 booleans all over the place is incredibly awkward and error-prone, I turned create/update/update_only_diff into a single enum that represents all of the valid combinations of those. This should make it impossible to have a similar bug elsewhere, as it'd have to fail to propagate the policy entirely and that's much more likely to be caught by tests.
See https://github.com/realm/realm-cocoa/issues/6321.
=> Properly propagate update_only_diff through List::assign()

src/impl/results_notifier.cpp, tests/realm.cpp
It now holds onto several transactions that also need to be closed.
=> Add some missing things to ResultsNotifier::release_data()

src/keypath_helpers.hpp, tests/sync/partial_sync.cpp
Required for realm-js to be able to use this rather than its own copy of the function. Also renames the function to a more accurate name since it now doesn't only do backlinks.
=> Populate public -> column names in keypath mappings

src/sync/impl/sync_client.hpp, src/sync/sync_config.hpp, src/sync/sync_manager.cpp, src/sync/sync_manager.hpp, src/sync/sync_session.cpp, src/sync/sync_session.hpp, tests/realm.cpp, tests/sync/file.cpp, tests/sync/partial_sync.cpp, tests/sync/permission.cpp, tests/sync/session/connection_change_notifications.cpp, tests/sync/session/session.cpp, tests/sync/session/wait_for_completion.cpp, tests/sync/sync_manager.cpp, tests/sync/user.cpp, tests/util/test_file.cpp, tests/util/test_file.hpp
This does a few things:
1. Change SyncManager::configure() to take a struct because the number of arguments it took was getting unwieldy, and then fiddle with how SyncManager stores the config settings internally.
2. Expose more of the options in sync::Client::Config to be customized via SyncManager. `ping_keepalive_period`/`pong_keepalive_timeout` were specifically requested by customers who wanted more responsive connection state updates and `connect_timeout` is made interesting by the next change; the other two probably aren't interesting to customize.
3. Pass the actual error code to download wait callbacks rather than "operation aborted", which indirectly makes asyncOpen() report actual error codes.
4. Add an option to cancel async waits on non-fatal errors in addition to fatal …
=> Expose additional sync client configuration options

src/keypath_helpers.hpp, src/object_accessor.hpp, src/object_schema.cpp, src/object_schema.hpp, src/object_store.cpp, src/object_store.hpp, src/schema.cpp, src/schema.hpp, src/shared_realm.cpp, tests/CMakeLists.txt, tests/migrations.cpp, tests/realm.cpp, tests/schema.cpp
Similar to how is done for column keys on Property.
Cocoa has a parallel set of schema data structures which we cache various things on. One of these is the TableRef for each ObjectSchema which is lazily stored the first time it's used. This is pretty important for performance (disabling the caching doubles the runtime of some basic operations), but it doesn't work for frozen Realms. To be thread-safe, we'd need to either add locking or eagerly look up TableRefs for each ObjectSchema.
Fortunately with core 6 we can get away with storing a TableKey rather than a TableRef, and pushing the logic here makes populating the `table_key` property eagerly nearly free, as we're already doing the complicated and expensive parts for column keys. This also lets us eliminate a few places where we look …
=> Store the table key on ObjectSchema

src/impl/realm_coordinator.cpp, src/impl/realm_coordinator.hpp, src/sync/sync_config.hpp, src/sync/sync_session.cpp
This was part of the sync 1.x -> 2.0 migration, where we needed to discover that it was an old file being opened very early in the process to hit the correct error recovery path. That error recovery path no longer exists at all, so it's now just pointless.
=> Remove sync history validation

CMake/CompilerFlags.cmake, src/CMakeLists.txt, src/execution_context_id.hpp, src/impl/collection_notifier.cpp, src/impl/collection_notifier.hpp, src/impl/realm_coordinator.cpp, src/impl/realm_coordinator.hpp, src/list.cpp, src/list.hpp, src/object.cpp, src/object.hpp, src/object_accessor.hpp, src/object_schema.cpp, src/object_schema.hpp, src/property.hpp, src/results.cpp, src/results.hpp, src/schema.cpp, src/schema.hpp, src/util/checked_mutex.hpp, src/util/copyable_atomic.hpp, src/util/tagged_bool.hpp, tests/util/test_file.cpp
Results being lazily evaluated makes reading from it from multiple threads without any locking unsafe even when it's backed by a frozen Realm. To fix this we need to introduce some locking around the members which can be mutated on read. Benchmarking indicated a measurable slowdown from always doing the locking (~10% time increase for iterating over query results from obj-c), so it uses an "optional" mutex which is a no-op for non-frozen realms and only actually locks when the realm is frozen.
The complicated control flow inside Results made figuring out where exactly locks were needed (and needed to not be present to avoid deadlocks), so I introduced the use of clang's [Thread Safety Analysis annotations](https://clang.llvm.org/docs/ThreadSafetyAnalysis.html) which perform static checks …
=> Fix thread-safety issues with frozen Results

tests/benchmarks/main.cpp, tests/main.cpp
Catch2 is updated from v2.10.0 to v2.11.1. General fixes and improvements; the release notes are here: https://github.com/catchorg/Catch2/releases
=> Update catch2 to v2.11.1

src/impl/collection_change_builder.cpp, src/impl/collection_change_builder.hpp, src/impl/collection_notifier.hpp, src/impl/results_notifier.cpp, src/impl/results_notifier.hpp, src/list.cpp, src/results.cpp, src/results.hpp, tests/collection_change_indices.cpp, tests/primitive_list.cpp, tests/thread_safe_reference.cpp, workflow/test_coverage.sh
As Lists can no longer be accessed via Query/TableView, Lists which have been wrapped in a 
Results (normally for sort/distinct) need their own special handling for notifications.
The logic for this is very similar to sorted notifications in core 5, with manual updating of row indices to reflect insertions/deletions prior to diffing.
=> Restore support for notifications on sorted primitive lists

src/sync/app.cpp, src/sync/app.hpp, src/sync/app_credentials.cpp, src/sync/app_credentials.hpp, src/sync/generic_network_transport.cpp, src/sync/generic_network_transport.hpp, src/sync/impl/sync_metadata.cpp, src/sync/impl/sync_metadata.hpp, src/sync/sync_manager.cpp, src/sync/sync_user.cpp, src/sync/sync_user.hpp, tests/CMakeLists.txt, tests/sync/app.cpp, tests/util/test_utils.cpp
Addressing review comments on https://github.com/realm/realm-object-store/pull/921
There's still outstanding work, including:
=> App updates

CMake/CompilerFlags.cmake, src/list.cpp, src/list.hpp, src/object.cpp, src/results.cpp, src/results.hpp, src/server/global_notifier.cpp, src/shared_realm.cpp, src/shared_realm.hpp, src/sync/partial_sync.cpp, src/thread_safe_reference.cpp, src/thread_safe_reference.hpp, tests/thread_safe_reference.cpp, workflow/build.sh, workflow/test_coverage.sh
With core 5 this was forbidden, but with core 6 it mostly works fine. The exception is with objects which didn't exist yet at the start of the write transaction, as the object key doesn't actually exist in the stored version. For `ThreadSafeReference<Object>` and `ThreadSafeReference<List>` this has a straightforward fix of refreshing the target Realm if it's at the version which the relevant write was started at before trying to hand over the object/list. For Results derived from a List or LinkingObjects, Query doesn't expose the required members to do this so just disallow it for now.
=> Fix some bugs with creating ThreadSafeReference inside write transactions

src/sync/app.hpp
Adds a series of structs and definitions that will allow a user to use functionality based on specific providers that allow it. The two providers that Stitch currently has additional functionality for are:
- `UserAPIKey`
- `UsernamePassword`
See: [CoreUserAPIKeyAuthProviderClient.swift](https://github.com/mongodb/stitch-ios-sdk/blob/master/Core/StitchCoreSDK/Sources/StitchCoreSDK/Auth/Providers/UserAPIKey/CoreUserAPIKeyAuthProviderClient.swift)
See: [CoreUserPasswordAuthProviderClient.swift](https://github.com/mongodb/stitch-ios-sdk/blob/master/Core/StitchCoreSDK/Sources/StitchCoreSDK/Auth/Providers/UserPassword/CoreUserPasswordAuthProviderClient.swift)
Bindings would call this as: 
```cpp
app.provider_client<UsernamePasswordProviderClient>().register_email(
"bar@foo.com",
"password", …
```
=> Add auth provider client stubs

src/sync/app.cpp
This should fix the segfault in JS.
=> Pass shared pointer (for sync user) by value in log_in

src/sync/app.cpp, src/sync/app.hpp, tests/sync/app.cpp
This PR adds support for logging individual users out instead of only the current user.
Note: Does not run the tests until Authentication tests are enabled.
=> Add support for logging specific user out

CMake/CodeCoverage.cmake, Jenkinsfile
Previously, the report was empty. This gets it working again, even linking properly to source files so you don't have to run coverage builds locally to see what is missing test coverage. The Jenkins Cobertura plugin tracks coverage over time as well so we can see trends. Current coverage:
=> Fix cobertura coverage reports

Jenkinsfile
Related discussion: https://mongodb.slack.com/archives/CKW2HG3M0/p1584972772024800?thread_ts=1584965550.009700&cid=CKW2HG3M0
=> manually pin a docker version for cache reasons

src/sync/app.cpp, src/sync/app.hpp, tests/sync/app.cpp
This gives the `UserAPIKeyProviderClient` methods a user parameter so that the operations are explicit as to which user they operate on instead of assuming the current user.
=> UserAPIKeyProviderClient methods operate on a user

src/sync/app.cpp, src/sync/app.hpp, tests/sync/app.cpp
Using the entire ApiKey struct as argument added needless complexity to the Java SDK + we only use the ID anyway.
=> Only require ID for ApiKey provider

src/sync/app.cpp, src/sync/app.hpp, tests/sync/app.cpp
The use of Optional wasn't really needed and just makes the API harder to consume.
=> Remove Optional from create/fetch callbacks in ApiKeyAuthProvider

src/impl/object_accessor_impl.hpp, src/list.cpp, src/list.hpp, src/object.cpp, src/object.hpp, src/object_accessor.hpp, src/object_schema.cpp, src/object_schema.hpp, src/object_store.cpp, src/object_store.hpp, src/results.cpp, src/results.hpp, src/schema.cpp, src/schema.hpp, src/sync/app.hpp, src/sync/generic_network_transport.cpp, src/sync/generic_network_transport.hpp, src/sync/sync_user.cpp, src/thread_safe_reference.cpp, tests/list.cpp, tests/migrations.cpp, tests/object.cpp, tests/results.cpp, tests/schema.cpp
Only Object::create() was implemented, and mutating an object or list after creation didn't work. Migrations involving embedded tables didn't work correctly, and some schema validation was missing.
This changes the SDK API for embedded objects a bit. unbox_embedded() and create_embedded_obectj() are gone, and instead the context must implement create_embedded_object(), which uses the object and property passed to the context at construction time. CreatePolicy is now a struct of bools because there's an additional bit of data that needs to be passed along (whether we're in a create operation or add operation) which determines how we handle nested objects which are already managed by the realm (inside create() we copy existing managed embedded objects, but setting a link directly to a …
=> Implement missing parts of embedded objects

src/shared_realm.cpp, tests/realm.cpp
Example code which hit this:
std::vector<ObjectSchema> classes;
for (int i = 0; i < 10'000; ++i) {
classes.push_back({util::format("type %1", i), {
{"value", PropertyType::Int}
}});
}
InMemoryTestFile config;
config.cache = false;
config.automatic_change_notifications = false;
auto r = Realm::get_shared_realm(config);
r->update_schema(classes);
std::thread t([&] { Realm::get_shared_realm(config); });
while (true) {
r->begin_transaction(); r->commit_transaction();
}
Previously Realm::update_schema() would clear RealmCoordinator's schema cache, but not repopulate it. This was because populating it requires rereading it from the Realm, so it was optimal to defer doing that until it was next needed (i.e. the next time a Realm instance was obtained). However, this lead to a race condition: if …
=> Fix "previous <= m_schema_transaction_version_max" assertion failure

src/server/global_notifier.cpp
MSVC complains about ambiguous `=` operators with the `json` type because apparently `std::string` can be `=` with both another string, and an initializer list of characters, and `json` can be both.
=> Fix build on Visual Studio 2019

src/server/global_notifier.cpp
Fix build on Visual Studio 2019 (#980)
MSVC complains about ambiguous `=` operators with the `json` type because apparently `std::string` can be `=` with both another string, and an initializer list of characters, and `json` can be both.
=> Vs2019 build fixes

src/impl/realm_coordinator.cpp
Disables Client Resync which would make the server send an empty State Realm. Which in return would remove all locally defined schemas.
=> Disable Client Resync

src/keypath_helpers.hpp, tests/CMakeLists.txt, tests/results.cpp
These helper methods needed to be updated when changing to core v10.0.0-alpha.8 because of changes to `KeyPathElement`. However, this code was unused and untested at the object store level so didn't cause any build failures until the SDK's tried to update.
=> keypath helper update

src/sync/sync_session.hpp, tests/sync/partial_sync.cpp
This tries to cover all of the cases around pre-existing local Realm files that need some schema changes made for partial sync.
Reverting 2506970c20899ee264c99924978bbc2efb2c2f7e results in the following failures in these tests:
-------------------------------------------------------------------------------
Query-based sync schema initialization
open existing local Realm which has an older schema with dynamic schema
-------------------------------------------------------------------------------
/src/realm-object-store/tests/sync/partial_sync.cpp:1403
...............................................................................
/src/realm-object-store/tests/sync/partial_sync.cpp:1261: FAILED:
CHECK( table->get_column_index("created_at") != npos ) …
=> Add tests for partial sync schema init

src/sync/remote_mongo_collection.cpp, src/sync/remote_mongo_collection.hpp, tests/sync/app.cpp
This PR addressed a bug where `count` would return the amount of all documents in a collection if the query document did not exist. More tests have been added to check this. Another bug caught in this PR is to do with `sort` during a find operation.
=> Bug fix for count, add more robust tests

src/shared_realm.cpp
We have a unit test in Java that caught this https://github.com/realm/realm-java/pull/6838
I tried to create a similar test in Object Store, but so far failed, so I still haven't ruled out this is a bug in the Java SDK. But I thought I would make a PR nonetheless because no matter what, the ObjectStore code looks fishy. `transaction()` will attempt to create a ReadTransaction if one isn't already open, and doing that inside `close()` is definitely wasteful.
=> Fix close triggers reopening a Realm

src/sync/app.cpp, src/sync/app.hpp, src/sync/impl/sync_metadata.cpp, src/sync/impl/sync_metadata.hpp, src/sync/sync_manager.cpp, src/sync/sync_manager.hpp, src/sync/sync_user.cpp, src/sync/sync_user.hpp, tests/mongodb/auth_providers/anon-user.json, tests/mongodb/auth_providers/api-key.json, tests/mongodb/auth_providers/custom-function.json, tests/mongodb/auth_providers/local-userpass.json, tests/mongodb/functions/authFunc/config.json, tests/mongodb/functions/confirmFunc/config.json, tests/mongodb/functions/resetFunc/config.json, tests/mongodb/functions/sumFunc/config.json, tests/mongodb/services/BackingDB/config.json, tests/mongodb/services/BackingDB/rules/test_data.Dog.json, tests/mongodb/services/BackingDB/rules/test_data.Person.json, tests/mongodb/stitch.json, tests/sync/app.cpp, tests/sync/session/connection_change_notifications.cpp, tests/sync/session/session.cpp, tests/sync/session/wait_for_completion.cpp, tests/sync/sync_manager.cpp, tests/sync/user.cpp, tests/util/test_file.cpp
This PR will address sending a set of `options` in the body of the `log_in_with_credential`. The `options` in this PR just contain a `deviceId` parameter, which will be needed for services such as push notifications. 
Consumers of the Object Store will pass the deviceId into `App::Config`. Once a user has successfully logged in the deviceId will be passed to the `SyncUser`.
=> Add auth options to log_in_with_credential

src/index_set.hpp
This fixes the build error on windows universal ([example](https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-object-store/detail/PR-1011/19/pipeline)) on the new/upgraded CI nodes. There should be no functional difference.
```
C:\jenkins\workspace\realm_realm-object-store_PR-1011\src\index_set.hpp(192,39): error C4996: 'std::iterator<std::forward_iterator_tag,size_t,ptrdiff_t,size_t *,size_t &>': warning STL4015: The std::iterator class template (used as a base class to provide typedefs) is deprecated in C++17. (The <iterator> header is NOT deprecated.) The C++ Standard has never required user-defined iterators to derive from std::iterator. To fix this warning, stop deriving from std::iterator and start providing publicly accessible typedefs named iterator_category, value_type, …
```
=> change the way we implement an iterator for windows

src/util/event_loop_dispatcher.hpp, tests/util/event_loop.cpp
C++17 For the win!
I was about to start using this type a lot in realm-js, so I thought I'd make it a bit easier to use first.
=> Add C++17 deduction guides to EventLoopDispatcher

src/impl/apple/keychain_helper.cpp
With previous versions we stored the key with `kSecAttrAccessibleAlways`, and looking it up with `kSecAttrAccessibleAfterFirstUnlock` sometimes doesn't work. Fortunately there's no reason to actually include it in the search dictionary for lookup, and only for setting.
I was unable to write a test which reproduces the problem; storing with Always and then immediately looking up with AfterFirstUnlock works unfortunately.
Fixes https://github.com/realm/realm-cocoa/issues/6538.
=> Fix sync metadata key lookup failures

src/sync/app_utils.hpp
We were relying on exact matching for header text here, but the js sdk is using all lower case, so we were getting generic all generic error messages instead of being able to parse the errors out of the returned json.
=> case insensitive headers comparisons

src/sync/app.cpp, src/sync/remote_mongo_collection.cpp, src/sync/remote_mongo_collection.hpp, tests/sync/app.cpp
This PR addresses a bug fix. The bug is where a findOneAndX remote mongo call was passing up the filtering document with `query` instead of `filter` in the request body. Tests have also been added to make sure the unhappy path is captured
=> Fix remote mongo findOneAndX to use 'filter'

src/sync/sync_config.hpp, src/sync/sync_session.cpp
Seems this was forgotten as part of: https://github.com/realm/realm-object-store/pull/1025
Not handling this would otherwise break Realm Java
=> Add new protocol error to list of errors handled.

src/object_schema.cpp, tests/schema.cpp
This was an arbitrary restriction that I thought was imposed by the server but actually is fine.
=> Allow linking from embedded to top-level object types

src/sync/push_client.cpp, src/sync/push_client.hpp, src/sync/sync_manager.cpp, tests/sync/app.cpp
This PR addresses two issues:
- Remove the need for a registration token when deregistering an device using the `push_client`
- Ensure that the `access_token` is set before the `refresh_token` in the `get_user` call in `sync_manager`. As previously when the `refresh_token` was getting set first it allowed the sync client to start without an `access_token` due to each of the `update_X_token` trying to revive a session once they are set. This issue was prominent when calling log_in with a logged out user and attempting to create a sync connection.
=> Fix push client and change the token update order in sync_manager

src/sync/sync_session.cpp
This change is needed for msvc compiler to produce valid code that initializes the session state classes correctly.
=> fix msvc compiler glitch

src/sync/app_credentials.cpp, src/sync/app_credentials.hpp, tests/sync/app.cpp
Closes:
https://github.com/realm/realm-object-store/issues/1040
The current implementation receives a string payload, which is outdated. It should be a BsonDocument instead.
=> Add support for Bson documents to auth custom functions.

src/sync/sync_session.cpp, src/sync/sync_session.hpp, tests/sync/session/session.cpp
This PR addresses an issue where a sync session can not be established with an access token that is invalid. There is some small change in logic w.r.t how sync errors are handled and how a session is created once an error has been resolved.
=> Add fix for refreshing an expired access token on sync start

src/thread_safe_reference.cpp, src/thread_safe_reference.hpp, tests/thread_safe_reference.cpp
Not doing this made it possible to end up with 2+ DB instances for the same Realm file in the same process if the ThreadSafeReference's Transaction was the last thing keeping a DB alive.
It's unclear if this had any consequences besides increased memory usage.
=> Retain RealmCoordinator in ThreadSafeReference::Payload

src/sync/impl/sync_client.hpp, src/sync/sync_session.cpp, src/sync/sync_session.hpp, tests/sync/session/session.cpp
I am proposing this new feature as a solution to a problem identified by @RedBeard0531, namely that when a unit test needs to delete a Realm file, it has no way of ensuring that the Realm file is closed by everyone before deleting.
One way to solve the problem in Realm JS, is to expose `Realm::shutdown_and_wait()` for the purpose of testing, and have tests call it before deleting Realm files. If done this way, it will be necessary to call `shutdown_sync()` before calling `close()`.
=> Added Realm::shutdown_sync() which waits for Realm file to be closed

src/sync/remote_mongo_collection.cpp
This would never actually change behavior since it would always pass a length
larger than desired which would automatically be interpreted as stopping at
the end of the string. But it seems better to either pass the real desired
length, or use the default of npos. This was an issue in the JS port of this
code for realm-web, and I'd prefer to keep the differences between the
implementations to a minimum.
=> Don't pass bogus length to string_view::substr()

CMake/CodeCoverage.cmake, Jenkinsfile, src/sync/sync_manager.cpp, src/sync/sync_user.hpp, tests/util/test_file.hpp, workflow/test_coverage.sh
This cuts the runtime of the sync-enabled test suite from 4 minutes to 4 *seconds* since nearly all of the time was spent creating, opening, closing, and then deleting the metadata realm without ever actually reading anything from it.
I also ported over the changes to fix code coverage generation from v10 as I wanted to make sure that there wasn't any sync metadata functions only accidentally being covered by other tests.
=> Disable sync metadata storage for most tests

src/impl/results_notifier.cpp, tests/results.cpp
Core 6 changed how TableViews were passed from ResultsNotifier to Results to be pull-based rather than push based. With Core 5, ResultsNotifier mutated the parent Results to update the TableView as part of change notification delivery, while now Results gets the TableView from the ResultsNotifier when the user reads from the Results and forces a re-evaluation of the query. This change simplified the data flow a lot, but meant that if the Results is never actually read from, the TableView would sit around in the ResultsNotifier forever, and continue to pin that version.
To fix this, add a check to see if there's a stale TV that went unused and if so discard it and release the version pin.
=> Fix a version pinning issue with Results

src/keypath_helpers.hpp
Fixes #1072 
The `LinkPathPart` constructor throws `NoSuchTable` when `tr` is invalid. Due to that only being used in QBS code that's going away + my limited C++ skills, I haven't added any tests, but @ironage or @fealebenpae feel free to add if you feel it's worth it.
=> ROBJSTORE-109: Don't construct LinkPathPart with invalid tableref

src/sync/sync_manager.cpp, tests/sync/user.cpp
This PR addresses a bug where the `identities` of a user were not being set on creation of an `App` due to the fact that `SyncManager::init_metadata` did not call `update_identities` for each persisted user.
Fixes: https://github.com/realm/realm-cocoa/issues/6647
=> Fix bug where a users identities are not being set on init_metadata

src/impl/realm_coordinator.cpp, src/impl/realm_coordinator.hpp, src/impl/weak_realm_notifier.cpp, src/impl/weak_realm_notifier.hpp, src/shared_realm.cpp, src/shared_realm.hpp, src/util/android/scheduler.hpp, src/util/apple/scheduler.hpp, src/util/generic/scheduler.hpp, src/util/scheduler.cpp, src/util/scheduler.hpp, src/util/uv/scheduler.hpp, tests/list.cpp, tests/migrations.cpp, tests/object.cpp, tests/primitive_list.cpp, tests/realm.cpp, tests/results.cpp, tests/thread_safe_reference.cpp, tests/transaction_log_parsing.cpp
A cached realm will now be returned from `RealmCoordinator::get_shared_realm()` if these conditions are met:
- config.cache is true (default)
- config.scheduler identifies itself as meeting the comparison criteria, this is implementation dependant, but can be a thread id check for example.
Fixes https://github.com/realm/realm-object-store/issues/1069
=> resurrect realm caching

src/impl/results_notifier.cpp, tests/results.cpp
When we import a TableView into an active write transaction we don't actually know if the TV is up to date, as we don't keep track of which tables have been modified so far in the transaction. This means that we just can't use the background TV if it isn't picked up before starting the write transaction, or it may have stale results if it's imported after a change that effects it.
Fixes https://github.com/realm/realm-cocoa/issues/6721.
=> Don't try to deliver async query results inside a write transaction

src/impl/realm_coordinator.cpp
While debugging some caching issues, I noticed that we always return a cached Realm when there's no scheduler, which is probably not what we want to do.
=> Don't cache realms without a scheduler

src/sync/impl/sync_file.cpp, src/sync/impl/sync_file.hpp, src/sync/sync_manager.cpp, tests/sync/file.cpp, tests/sync/sync_manager.cpp
This PR refactor ObjectStore, so it only uses `local_uuid` for legacy Realms. For future Realms, it uses the global server UUID in the path.
=> Use global id to compose Realm path

src/impl/realm_coordinator.cpp, src/shared_realm.cpp, src/util/scheduler.cpp, src/util/scheduler.hpp, tests/realm.cpp, tests/results.cpp, tests/thread_safe_reference.cpp
Without this change, we would always use the first cached frozen Realm, regardless of whether it's frozen at the required version or not.
Alternatively, we could pass the version in `do_get_cached_realm`, but felt that using the scheduler was a cleaner solution.
=> Add the version to the frozen scheduler

src/util/apple/scheduler.hpp
There's no public API to find out if a dispatch queue is serial or concurrent. On more recent OS versions we can check the class to determine it, but this doesn't work on older versions.
It seems fairly safe to skip the checks on old OSes since the only way it'd go uncaught is if a developer tests exclusively on very old devices (and never in the simulator or recent devices) or has separate code paths for old OS versions.
Fixes https://github.com/realm/realm-cocoa/issues/6735.
=> Skip validating dispatch queue types on older OSes

src/sync/app.cpp, src/sync/app.hpp, tests/sync/app.cpp
Add support for calling the custom confirmation function from the SDKs
=> Custom confirmation logic support

src/sync/app.cpp, src/sync/sync_user.cpp, tests/sync/app.cpp, tests/sync/user.cpp
When we log out and empty a users access/refresh token we do not persist that to the metadata realm. Therefor on the next startup for example, we still have the tokens, breaking some logic that requires both access & refresh tokens to be empty for a logged out user
=> Add ability for removing a users access/refresh token on log_out

CMake/RealmCore.cmake, src/CMakeLists.txt
With XCode 12, we get an error when building for simulator but linking against iOS's zlib. @fealebenpae moved things around and it now works 😄
=> Move finding zlib around

CMake/RealmCore.cmake, src/CMakeLists.txt
Reverts realm/realm-object-store#1090
While this did work for iOS, it broke android builds and turned out to be unnecessary as the iOS fix was to disable ARM builds for the simulator.
=> Revert "Move finding zlib around"

src/sync/app_credentials.cpp, src/sync/app_credentials.hpp
.NET doesn't have a way to pass a bson document down to native without essentially serializing it to json in managed code, then parsing it in the native wrappers, only to have OS serialize it back to json. This introduces an overload that eliminates the extra deserialization and serialization step.
Based on #1094, but will rebase on v10 once that goes in.
=> Expose credentials::function with string argument

src/sync/app.cpp, tests/sync/app.cpp
Updated parameters as per the Stitch rebrand to Realm Deprecation/EOL Notes:
- `stitch_request` to `baas_request`
- `stitch_at ` to `baas_at`
=> Update API calls to use the new Realm endpoints as per Stitch rebranding

src/object.cpp, src/shared_realm.hpp
This is an attempt to flush out some NoSuchTable exceptions which we do not understand.
It is based on the assumption that one way of getting a NoSuchTable exception, is when accessing an object after the associated Transaction object in Core has been released. The assert checks for any faulty association between the object accessor and the Realm object (representing/holding the transaction).
=> add a check to detect if an Object is created with an Obj, but without a valid Transaction.

src/sync/remote_mongo_collection.cpp, src/sync/remote_mongo_collection.hpp, tests/sync/app.cpp
The insertedId/insertedIds returned by the mongo server for calls to insert_one/insert_many can be any valid value. This changes our implementation of those functions to reflect that.
=> ROBJSTORE-124 insert functions should return non-ObjectID inserted IDs

src/sync/app.cpp, src/sync/app.hpp, src/sync/remote_mongo_client.cpp, src/sync/remote_mongo_client.hpp, src/sync/remote_mongo_collection.cpp, src/sync/remote_mongo_collection.hpp, src/sync/remote_mongo_database.cpp, src/sync/remote_mongo_database.hpp, src/sync/sync_user.cpp, src/sync/sync_user.hpp, tests/sync/app.cpp
This moves the factory for MongoClient to SyncUser from App so that mongo operations are performed by a specific user rather than whatever the current user of the App is. It also renamed RemoteMongoClient/DatabaseCollection to just MongoClient/Database/Collection.
=> ROBJSTORE-125 Move MongoClient under SyncUser

src/CMakeLists.txt, src/sync/app.cpp, src/sync/app_utils.cpp, src/sync/app_utils.hpp, src/sync/generic_network_transport.hpp, src/sync/push_client.cpp, tests/sync/app.cpp
This PR addresses an uncaught bug. The bug is where a http response which contains `application/json` would not write the http status to an AppError object. Therefor if the user got a 401 http response because of a bad token we would never be able to catch it in `App::handle_auth_failure` as there is no http status code to look up.
In this PR I've added `http_status_code` as an optional attribute of `AppError`. I have also wrapped the static `check_for_errors` method in a class.
Addresses: https://github.com/realm/realm-object-store/issues/1119
=> Add http_status_code as a param to AppError.

src/sync/sync_session.cpp, src/sync/sync_session.hpp
Opening this in lieu of #1054.
=> ROBJSTORE-98 Implement precise and unbatched notification of sync completion events

src/CMakeLists.txt, src/sync/mongo_client.cpp, src/sync/mongo_client.hpp, src/sync/mongo_collection.cpp, src/sync/mongo_collection.hpp, src/sync/mongo_database.cpp, src/sync/mongo_database.hpp, src/sync/sync_user.cpp, tests/mongodb/graphql/config.json, tests/sync/app.cpp, tests/sync/remote_mongo_tests.cpp
This PR just renames the remote_mongo_x files to mongo_x for clarity, as we have now remove the 'Remote' prefix from any remote MongoDB classes.
=> Rename remote_mongo_x files

.gitignore, src/impl/windows/external_commit_helper.cpp, src/impl/windows/external_commit_helper.hpp
don't close the mapped file handle cause the mapped file can not be opened from another process. This fixes the sharing of memory needed to synchronize realm file access between windows processes
=> fix SharedMemory on Win32 platforms

.gitignore, src/impl/windows/external_commit_helper.hpp
fix SharedMemory on Win32 targets
https://github.com/realm/realm-object-store/pull/1129/files into core-6
don't close the mapped file handle cause the mapped file can not be opened from another process. This fixes the sharing of memory needed to synchronize realm file access between windows processes
=> fix SharedMemory on win32

src/sync/sync_manager.cpp
The sync client may still be using that directory so it needs to be stopped first. This is probably the source of occasional make_dir() errors in the Cocoa sync tests.
=> Stop the sync client before tearing down the sync file manager

src/sync/impl/sync_file.cpp
This fixes path generation on windows
the old version generates a path like so: c:\my_path/my_component/path
the pr version generates a path like so: c:\my_path\my_component\path
=> fix-win-paths

src/impl/realm_coordinator.cpp
This fixes multi-process sync when one process writes to the realm and notifies the current process that changes occured.
=> Fix multi process sync

CMakeSettings.json, src/impl/realm_coordinator.cpp, src/impl/windows/external_commit_helper.cpp, src/impl/windows/external_commit_helper.hpp
Normalize Windows kernel object names casing to account for windows drive letter case-insenstivity
added Visual Studio generated CMakeSettings.json to allow building and runing tests.exe from whithin Visual Studio
=> Normalize Windows kernel object names casing

src/object_accessor.hpp
Fixes a crash when trying to build an error message with a null primary key default value. 
The crash is due to assert in realm::util::Optional `Assertion failed: m_engaged`
=> fix-crash-with-optional-primary-key

src/schema.cpp, tests/schema.cpp
It was [reported](https://jira.mongodb.org/browse/RJAVA-710) that a cycle is incorrectly detected in the case of a diamond pattern of paths; eg. given the relationship graph A->B->C, and A->D->C. 
Also fixed detecting cycles through top level objects, as this should be allowed by the server. Eg. Given a top level object with an embedded object which also has a link to the same top level object, this is not considered a loop we should restrict.
=> update embedded object cycle detection

src/impl/windows/external_commit_helper.cpp
This is a precondition when calling notify_all and fixes a dead lock in Electron on Windows
=> hold the mutex while calling notify_all

src/sync/sync_manager.cpp, src/sync/sync_user.cpp, tests/sync/app.cpp
Fixes https://github.com/realm/realm-core/issues/4142
I think this is all that is required, but I'm not super familiar with the Removed user state and how it differentiates from the logged out state. I also considered doing the user removal at this point, and creating a new object instance but I didn't want to deviate the behaviour from what the logged out state does. So I'll ask reviewers to please confirm that this seems correct.
=> Allow revival of removed users
